Gemfile
spec/mongo_orchestration_spec.rb
spec/spec_helper.rb
spec/support/mongo_orchestration.rb
spec/support/mongo_orchestration/requestable.rb
spec/support/mongo_orchestration/standalone.rb

A first stab at making a Mongo Orchestration standalone resource available in our tests.

Standalone Mongo Orchestration

---

lib/mongo/client.rb
lib/mongo/server_preference.rb
lib/mongo/server_preference/nearest.rb
lib/mongo/server_preference/primary_preferred.rb
lib/mongo/server_preference/secondary.rb
lib/mongo/server_preference/secondary_preferred.rb
lib/mongo/server_preference/selectable.rb
lib/mongo/uri.rb
spec/mongo/client_spec.rb
spec/mongo/database_spec.rb
spec/mongo/server_preference_spec.rb
spec/mongo/uri_spec.rb
spec/support/shared/server_preference.rb

Add local_threshold_ms and server_selection_timeout_ms options to client and server pref as per the server selection spec.

RUBY-762 Add local_threshold_ms and server_selection_timeout_ms options

---

lib/mongo/collection/view/iterable.rb
lib/mongo/collection/view/readable.rb
lib/mongo/database.rb
lib/mongo/server_preference.rb
lib/mongo/server_preference/nearest.rb
lib/mongo/server_preference/primary.rb
lib/mongo/server_preference/primary_preferred.rb
lib/mongo/server_preference/secondary.rb
lib/mongo/server_preference/secondary_preferred.rb
lib/mongo/server_preference/selectable.rb
spec/mongo/collection/view/readable_spec.rb
spec/mongo/database_spec.rb
spec/mongo/server_preference/nearest_spec.rb
spec/mongo/server_preference/primary_preferred_spec.rb
spec/mongo/server_preference/primary_spec.rb
spec/mongo/server_preference/secondary_preferred_spec.rb
spec/mongo/server_preference/secondary_spec.rb

Add in read preference option to command helpers #distinct and #count
Also, ignore read preference for topology "Single"

RUBY-850 and RUBY-851

---

lib/mongo/operation/bulk_delete/result.rb
lib/mongo/operation/bulk_insert/result.rb
lib/mongo/operation/bulk_update/result.rb
lib/mongo/operation/result.rb

Part of the changes for ongoing Mongoid integration.

RUBY-846: Rename first to not conflict with Enumerable

---

lib/mongo/server.rb
lib/mongo/server/description.rb
lib/mongo/server/description/inspector.rb
lib/mongo/server/monitor.rb
lib/mongo/server_selector/selectable.rb
spec/mongo/server/description_spec.rb
spec/mongo/server_discovery_and_monitoring_spec.rb
spec/mongo/server_selection_rtt_spec.rb
spec/mongo/server_selector/nearest_spec.rb
spec/mongo/server_selector/primary_preferred_spec.rb
spec/mongo/server_selector/primary_spec.rb
spec/mongo/server_selector/secondary_preferred_spec.rb
spec/mongo/server_selector/secondary_spec.rb
spec/spec_helper.rb
spec/support/server_selection/rtt/first_value.yml
spec/support/server_selection/rtt/first_value_zero.yml
spec/support/server_selection/rtt/value_test_1.yml
spec/support/server_selection/rtt/value_test_2.yml
spec/support/server_selection/rtt/value_test_3.yml
spec/support/server_selection/rtt/value_test_4.yml
spec/support/server_selection/rtt/value_test_5.yml
spec/support/server_selection_rtt.rb
spec/support/shared/server_selector.rb

..as per server selection spec

RUBY-853 Use moving average round trip time

---

.travis.yml
lib/mongo.rb
spec/spec_helper.rb

Running the spec suite on Travis with a matrick including MongoDB 2.4, 2.6, and 3.0

Travis Multiple Mongo CI Matrix

---

lib/mongo/server_selector/selectable.rb
spec/mongo/server_selection_spec.rb
spec/mongo/server_selector_spec.rb

- why was there a todo to test for compact on this line?

RUBY-854 Scan cluster if no server is found

---

lib/mongo/server/monitor.rb
spec/mongo/server/monitor_spec.rb

https://jira.mongodb.org/browse/RUBY-879

RUBY-879: Implement minHeartbeatFrequency at 500ms

---

lib/mongo/collection/view/writable.rb
lib/mongo/operation/write/update.rb
spec/mongo/collection/view/writable_spec.rb

RUBY-881 Add upsert option to #update_many, #update_one, #replace_one

---

lib/mongo/collection/view/aggregation.rb
lib/mongo/collection/view/map_reduce.rb
lib/mongo/operation/aggregate.rb
lib/mongo/operation/map_reduce.rb
spec/mongo/collection/view/aggregation_spec.rb
spec/mongo/collection/view/map_reduce_spec.rb

RUBY-933 Fix passing options to MapReduce and Aggregate operations

---

lib/mongo/uri.rb
spec/mongo/uri_spec.rb
spec/support/connection_string_tests/invalid-uris.yml
spec/support/connection_string_tests/valid-unix_socket-absolute.yml
spec/support/connection_string_tests/valid-unix_socket-relative.yml
spec/support/connection_string_tests/valid-warnings.yml

Yet another refactor to the URI class after changes to the spec.

RUBY-951 Update YAML tests and refactor URI class

---

lib/mongo/collection/view/readable.rb

We started doing failover testing against HEAD of the new driver and realized these two cases were missing from retry. We tested my branch and it works correctly.

Retry for count and distinct commands if there is a connection error.

---

lib/mongo/server/connectable.rb
lib/mongo/server/connection.rb
lib/mongo/server/monitor/connection.rb
lib/mongo/socket.rb
lib/mongo/socket/ssl.rb
spec/mongo/socket/ssl_spec.rb

RUBY-1012 RUBY-1011 Fix SSL reconnect

---

lib/mongo/grid/fs_bucket.rb

Reasoning is here: https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#before-write-operations

Must find one on files collection to comply with GridFS spec

---

lib/mongo/client.rb

State that :w can be Integer or String.

---

lib/mongo/collection/view/builder/op_query.rb
spec/mongo/collection/view/builder/op_query_spec.rb
spec/mongo/collection/view/readable_spec.rb

Thanks to @jonhyman for the regression test.

Fix projection regression in driver when using on server < 3.2

---

lib/mongo/collection/view/readable.rb
spec/mongo/collection/view/readable_spec.rb

https://github.com/mongodb/mongoid/blob/master/lib/mongoid/contextual/mongo.rb#L558-L562

[v 2.3.0] RUBY-1080 Add Collection::View#cursor_type

---

lib/mongo/dbref.rb
lib/mongo/grid/file/chunk.rb
lib/mongo/grid/file/info.rb
lib/mongo/operation/write/command/insert.rb
lib/mongo/protocol/bit_vector.rb
lib/mongo/protocol/insert.rb
lib/mongo/protocol/message.rb
lib/mongo/protocol/serializers.rb
mongo.gemspec
spec/mongo/collection_spec.rb
spec/mongo/operation/write/command/insert_spec.rb

This will pass tests when [this pull request](https://github.com/mongodb/bson-ruby/pull/59) against the bson gem is merged.

[v 2.3.0] RUBY-1092 Validate keys when inserting documents

---

lib/mongo/error/no_server_available.rb
lib/mongo/server_selector/selectable.rb
spec/mongo/server_selector_spec.rb

...not configurable on a ServerSelector

RUBY-1135 local_threshold should be taken from the client/cluster

---

docs/contribute.txt
docs/includes/older-server-versions-unsupported.rst
docs/includes/ruby-driver-compatibility-full-language.rst
docs/includes/ruby-driver-compatibility-full-mongodb.rst
docs/includes/ruby-driver-compatibility-matrix-language.rst
docs/includes/ruby-driver-compatibility-matrix-mongodb.rst
docs/includes/unicode-checkmark.rst
docs/index.txt
docs/installation.txt
docs/quick-start.txt
docs/reference/additional-resources.txt
docs/reference/driver-compatibility.txt
docs/ruby-driver-tutorials.txt
docs/tutorials/ruby-driver-admin-tasks.txt
docs/tutorials/ruby-driver-aggregation.txt
docs/tutorials/ruby-driver-bulk-operations.txt
docs/tutorials/ruby-driver-collection-tasks.txt
docs/tutorials/ruby-driver-create-client.txt
docs/tutorials/ruby-driver-crud-operations.txt
docs/tutorials/ruby-driver-geospatial-search.txt
docs/tutorials/ruby-driver-gridfs.txt
docs/tutorials/ruby-driver-indexing.txt
docs/tutorials/ruby-driver-projections.txt
docs/tutorials/ruby-driver-text-search.txt

Updated with just the ruby driver specific docs

Add docs for ruby driver manual

---

lib/mongo/operation/write/bulk/mergable.rb
lib/mongo/protocol/delete.rb
lib/mongo/protocol/get_more.rb
lib/mongo/protocol/insert.rb
lib/mongo/protocol/kill_cursors.rb
lib/mongo/protocol/message.rb
lib/mongo/protocol/query.rb
lib/mongo/protocol/update.rb
lib/mongo/server/connectable.rb
lib/mongo/server/connection_pool.rb
lib/mongo/server/monitor.rb
lib/mongo/socket.rb
lib/mongo/uri.rb

Hi.
We run ruby in verbose mode and we see a lot of warnings, these 4 commits fix the most of them.

Fix warnings in verbose mode

---

docs/index.txt
docs/installation.txt

Docs: Update gem install + update index.txt for mongoid

---

lib/mongo/collection.rb
lib/mongo/collection/view.rb
lib/mongo/collection/view/aggregation.rb
lib/mongo/collection/view/iterable.rb
lib/mongo/collection/view/map_reduce.rb
lib/mongo/collection/view/readable.rb
lib/mongo/collection/view/writable.rb
lib/mongo/index/view.rb
spec/mongo/collection/view/aggregation_spec.rb
spec/mongo/collection/view/map_reduce_spec.rb
spec/mongo/collection/view/readable_spec.rb
spec/mongo/collection/view/writable_spec.rb
spec/mongo/collection_spec.rb

This makes supporting collation in Mongoid much simpler.

Refactor CRUD private API so that collation is an option of a Collection::View

---

README.md

This PR changes the build status badges to use SVG.

README: Use SVG badges for clarity [ci skip]

---

lib/mongo/auth/scram/conversation.rb
lib/mongo/auth/user.rb
lib/mongo/server/connection.rb
spec/mongo/auth/scram_spec.rb

Cache SCRAM-SHA-1 ClientKey

---

lib/mongo/collection/view/change_stream.rb
lib/mongo/session.rb
lib/mongo/session/server_session.rb
lib/mongo/session/session_pool.rb
spec/mongo/collection/view/change_stream_spec.rb
spec/mongo/session/server_session_spec.rb
spec/mongo/session/session_pool_spec.rb
spec/mongo/session_spec.rb

``#inspect`` added for:
ChangeStream
Session
ServerSession
SessionPool

RUBY-1273 Add #inspect on new objects

---

lib/mongo/client.rb
lib/mongo/cluster.rb
lib/mongo/cluster/periodic_executor.rb
lib/mongo/cluster/reapers/cursor_reaper.rb
lib/mongo/cluster/reapers/socket_reaper.rb
lib/mongo/server/connection.rb
lib/mongo/server/connection_pool.rb
lib/mongo/server/connection_pool/queue.rb
spec/mongo/cluster/cursor_reaper_spec.rb
spec/mongo/cluster/socket_reaper_spec.rb
spec/mongo/cluster_spec.rb
spec/mongo/cursor_spec.rb
spec/mongo/server/connection_pool/queue_spec.rb
spec/mongo/server/connection_pool_spec.rb
spec/mongo/server/connection_spec.rb
spec/support/authorization.rb

* Implement maxIdleTime
* Create socket reaper for closing stale sockets in a given connection pool.
* Create PeriodicExecutor that executes reaper methods at regular intervals in a background thread. Currently reapers are CursorReaper and SocketReaper.

RUBY-741 Implement socket max idle time

---

docs/tutorials/ruby-driver-sessions.txt
lib/mongo/operation/uses_command_op_msg.rb
lib/mongo/operation/write/command/delete.rb
lib/mongo/operation/write/command/insert.rb
lib/mongo/operation/write/command/update.rb
lib/mongo/session.rb
spec/mongo/collection_spec.rb
spec/mongo/operation/write/command/delete_spec.rb
spec/mongo/operation/write/command/insert_spec.rb
spec/mongo/operation/write/command/update_spec.rb
spec/support/shared/session.rb

RUBY-1302 Prohibit using unacknowledged writes with explicit sessions

---

lib/mongo/error/operation_failure.rb
lib/mongo/error/parser.rb
lib/mongo/operation/indexes/result.rb
lib/mongo/operation/map_reduce/result.rb
lib/mongo/operation/result.rb
spec/mongo/error/operation_failure_spec.rb
spec/mongo/error/parser_spec.rb

https://jira.mongodb.org/browse/RUBY-1331
Extracted from work for https://jira.mongodb.org/browse/RUBY-1333

Expose error code and code name for errors and write concern errors

---

lib/mongo/cluster.rb
lib/mongo/monitoring.rb
lib/mongo/server/monitor.rb

- Document Cluster and Monitoring constructor parameters better
- Correct documentation for Monitor#scan!

Documentation improvements

---

lib/mongo/cluster.rb
lib/mongo/cluster/topology.rb
lib/mongo/cluster/topology/replica_set.rb

This adds narrative regarding topology-cluster interactions and replica set name for replica set topology.
https://jira.mongodb.org/browse/RUBY-1332

Topology-related documentation improvements

---

docs/tutorials/ruby-driver-change-streams.txt
lib/mongo/collection/view/change_stream.rb
lib/mongo/operation/list_collections/result.rb

Minor spelling and formatting changes.
https://jira.mongodb.org/browse/RUBY-1333

Retryable writes-related documentation improvements

---

lib/mongo/collection/view/builder/aggregation.rb
lib/mongo/cursor.rb
lib/mongo/operation/get_more.rb
lib/mongo/operation/get_more/command.rb
lib/mongo/operation/get_more/legacy.rb
lib/mongo/protocol/get_more.rb
spec/lite_spec_helper.rb
spec/mongo/cluster/topology_spec.rb
spec/mongo/collection/view/change_stream_spec.rb
spec/mongo/cursor/builder/get_more_command_spec.rb
spec/mongo/cursor_spec.rb
spec/mongo/protocol/get_more_spec.rb
spec/mongo/retryable_writes_spec.rb
spec/spec_helper.rb
spec/spec_tests/retryable_writes_spec.rb
spec/support/crud.rb

This PR contains changes that were made as part of retryable writes work but aren't part of the ticket proper, to avoid making the next PR unreadable.
https://jira.mongodb.org/browse/RUBY-1333

Retryable writes prerequisites

---

lib/mongo/collection.rb
lib/mongo/database.rb
lib/mongo/database/view.rb

Change streams-related documentation tweaks

---

spec/mongo/auth/scram/negotiation_spec.rb

https://jira.mongodb.org/browse/RUBY-1372

RUBY-1372 Translate replica set option to correct uri parameter

---

lib/mongo/error.rb
lib/mongo/error/no_server_available.rb
lib/mongo/error/operation_failure.rb
lib/mongo/error/socket_error.rb
lib/mongo/error/socket_timeout_error.rb
lib/mongo/operation/aggregate/op_msg.rb
lib/mongo/operation/create/op_msg.rb
lib/mongo/operation/create_index/op_msg.rb
lib/mongo/operation/create_user/op_msg.rb
lib/mongo/operation/delete/op_msg.rb
lib/mongo/operation/distinct/op_msg.rb
lib/mongo/operation/drop/op_msg.rb
lib/mongo/operation/drop_database/op_msg.rb
lib/mongo/operation/drop_index/op_msg.rb
lib/mongo/operation/explain/op_msg.rb
lib/mongo/operation/find/op_msg.rb
lib/mongo/operation/get_more/op_msg.rb
lib/mongo/operation/indexes/op_msg.rb
lib/mongo/operation/insert/op_msg.rb
lib/mongo/operation/kill_cursors/op_msg.rb
lib/mongo/operation/list_collections/op_msg.rb
lib/mongo/operation/map_reduce/op_msg.rb
lib/mongo/operation/parallel_scan/op_msg.rb
lib/mongo/operation/remove_user/op_msg.rb
lib/mongo/operation/update/op_msg.rb
lib/mongo/operation/update_user/op_msg.rb
lib/mongo/operation/users_info/op_msg.rb
lib/mongo/session.rb
spec/mongo/transactions_examples_spec.rb
spec/support/authorization.rb

See the ticket description for the shell code being ported

RUBY-1340 Provide Transactions example for Docs

---

Gemfile
docs/tutorials/ruby-driver-change-streams.txt
lib/mongo/client.rb
lib/mongo/collection.rb
lib/mongo/collection/view/change_stream.rb
lib/mongo/collection/view/change_stream/retryable.rb
lib/mongo/cursor.rb
lib/mongo/database.rb
lib/mongo/error.rb
lib/mongo/error/change_stream_resumable.rb
lib/mongo/error/operation_failure.rb
lib/mongo/error/socket_error.rb
spec/integration/change_stream_spec.rb
spec/mongo/client_spec.rb
spec/mongo/collection/view/change_stream_integration_spec.rb
spec/mongo/collection/view/change_stream_spec.rb
spec/spec_helper.rb
spec/support/constraints.rb

https://jira.mongodb.org/browse/RUBY-1373

Start at operation time implementation

---

lib/mongo/socket.rb
lib/mongo/socket/ssl.rb

https://jira.mongodb.org/browse/RUBY-1364

Improve ssl read performance

---

spec/mongo/collection_spec.rb
spec/support/constraints.rb

RUBY-1405 Do not run parallelCollectionScan tests on server 4.1+

---

docs/tutorials/ruby-driver-change-streams.txt
docs/tutorials/ruby-driver-collection-tasks.txt

https://jira.mongodb.org/browse/RUBY-1422
https://jira.mongodb.org/browse/RUBY-1457

Change stream docs improvements

---

.evergreen/.evg.yml
.evergreen/evg-atlas.yml
.evergreen/functions.sh
.evergreen/run-atlas-tests.sh
.evergreen/run-tests.sh
docs/reference/driver-compatibility.txt
lib/mongo/socket/ssl.rb

https://jira.mongodb.org/browse/RUBY-1470

Jruby SNI support

---

spec/mongo/bulk_write_spec.rb
spec/mongo/collection/view/change_stream_spec.rb
spec/mongo/cursor_spec.rb
spec/support/client_registry.rb

Last part of https://jira.mongodb.org/browse/RUBY-1454.

Client registry #with handling

---

lib/mongo/server.rb
lib/mongo/server/monitor.rb
lib/mongo/server/monitor/app_metadata.rb
lib/mongo/server/monitor/connection.rb
spec/mongo/auth/cr_spec.rb
spec/mongo/auth/ldap_spec.rb
spec/mongo/auth/scram_spec.rb
spec/mongo/auth/x509_spec.rb
spec/mongo/cluster/topology/replica_set_spec.rb
spec/mongo/cluster/topology/sharded_spec.rb
spec/mongo/cluster/topology/single_spec.rb
spec/mongo/server/app_metadata_spec.rb
spec/mongo/server/connection_pool_spec.rb
spec/mongo/server/connection_spec.rb
spec/mongo/server/description_spec.rb
spec/mongo/server/monitor/app_metadata_spec.rb
spec/mongo/server/monitor/connection_spec.rb
spec/mongo/server_spec.rb
spec/spec_tests/server_selection_spec.rb
spec/support/shared/server_selector.rb

Part 1 - omit scram bits from ismaster on monitoring sockets

RUBY-1319 Handshake changes for SDAM and Auth

---

lib/mongo/client.rb
lib/mongo/cluster.rb
lib/mongo/cluster/topology/replica_set_no_primary.rb
lib/mongo/cluster/topology/sharded.rb
lib/mongo/cluster/topology/single.rb
lib/mongo/cluster/topology/unknown.rb
lib/mongo/collection/view/change_stream.rb
lib/mongo/event/base.rb
lib/mongo/monitoring/event/server_opening.rb
lib/mongo/monitoring/event/topology_changed.rb
lib/mongo/monitoring/event/topology_opening.rb
lib/mongo/server.rb

Label all experimental methods with a @note in addition, and set @since
to avoid inheriting the class's @since

yard does not recognize @api experimental

---

spec/integration/docs_examples_spec.rb
spec/mongo/collection_spec.rb
spec/mongo/operation/delete/command_spec.rb
spec/mongo/operation/delete/op_msg_spec.rb
spec/mongo/operation/delete_spec.rb
spec/mongo/operation/find/legacy_spec.rb
spec/mongo/operation/insert/command_spec.rb
spec/mongo/operation/insert/op_msg_spec.rb
spec/mongo/operation/insert_spec.rb
spec/mongo/operation/update/command_spec.rb
spec/mongo/operation/update/op_msg_spec.rb
spec/mongo/operation/update_spec.rb
spec/mongo/protocol/compressed_spec.rb

https://jira.mongodb.org/browse/RUBY-1450

Remove uses of op_msg_enabled?

---

spec/integration/connection_spec.rb
spec/integration/retryable_writes_spec.rb
spec/mongo/auth/cr_spec.rb
spec/mongo/auth/scram/conversation_spec.rb
spec/mongo/auth/scram_spec.rb
spec/mongo/auth/user/view_spec.rb
spec/mongo/bulk_write_spec.rb
spec/mongo/client_construction_spec.rb
spec/mongo/collection/view/aggregation_spec.rb
spec/mongo/collection/view/map_reduce_spec.rb
spec/mongo/collection/view/readable_spec.rb
spec/mongo/collection/view/writable_spec.rb
spec/mongo/collection/view_spec.rb
spec/mongo/collection_spec.rb
spec/mongo/cursor_spec.rb
spec/mongo/database_spec.rb
spec/mongo/grid/stream/write_spec.rb
spec/mongo/index/view_spec.rb
spec/mongo/operation/delete/op_msg_spec.rb
spec/mongo/operation/insert/op_msg_spec.rb
spec/mongo/operation/update/op_msg_spec.rb
spec/mongo/server/app_metadata_spec.rb
spec/mongo/socket/ssl_spec.rb
spec/spec_helper.rb
spec/spec_tests/change_streams_spec.rb
spec/spec_tests/retryable_writes_spec.rb
spec/support/change_streams.rb
spec/support/cluster_config.rb
spec/support/constraints.rb
spec/support/shared/session.rb

https://jira.mongodb.com/browse/RUBY-1450

RUBY-1450 Change test suite to always define all examples

---

spec/spec_tests/data/transactions/abort.yml
spec/spec_tests/data/transactions/error-labels.yml
spec/support/transactions/verifier.rb

…24fe89c1c3af81bab1862009ad for transactions tests

Fix remaining transaction test failure

---

.evergreen/.evg.yml
docs/tutorials/ruby-driver-create-client.txt
lib/mongo/client.rb
lib/mongo/collection/view/aggregation.rb
lib/mongo/collection/view/builder/map_reduce.rb
lib/mongo/collection/view/change_stream.rb
lib/mongo/collection/view/iterable.rb
lib/mongo/collection/view/map_reduce.rb
lib/mongo/collection/view/readable.rb
lib/mongo/cursor.rb
lib/mongo/database.rb
lib/mongo/database/view.rb
lib/mongo/error/operation_failure.rb
lib/mongo/index/view.rb
lib/mongo/operation/list_collections/result.rb
lib/mongo/retryable.rb
lib/mongo/server.rb
lib/mongo/session.rb
spec/integration/sdam_error_handling_spec.rb
spec/lite_spec_helper.rb
spec/mongo/client_construction_spec.rb
spec/mongo/client_spec.rb
spec/mongo/collection/view/change_stream_spec.rb
spec/mongo/collection/view/readable_spec.rb
spec/mongo/retryable_spec.rb
spec/spec_tests/retryable_reads_spec.rb
spec/support/authorization.rb
spec/support/client_registry.rb
spec/support/crud/test.rb
spec/support/spec_config.rb

https://jira.mongodb.com/browse/RUBY-1562

RUBY-1562 Retryable Reads implementation

---

lib/mongo/error/sdam_error_detection.rb
lib/mongo/operation/result.rb
lib/mongo/operation/shared/executable.rb
spec/integration/sdam_error_handling_spec.rb
spec/integration/step_down_spec.rb
spec/support/cluster_tools.rb
spec/support/common_shortcuts.rb
spec/support/event_subscriber.rb

Update driver to match current specification

RUBY-1572 Connections survive primary step down

---

lib/mongo/server/connectable.rb
lib/mongo/server/connection.rb
lib/mongo/server/monitor/connection.rb
lib/mongo/socket/ssl.rb
spec/README.md

https://jira.mongodb.com/browse/RUBY-1794

RUBY-1794 Verify that driver can connect to server with full TLS verification

---

docs/tutorials/ruby-driver-change-streams.txt
lib/mongo/collection/view/change_stream.rb
lib/mongo/cursor.rb
lib/mongo/operation/aggregate/result.rb
lib/mongo/operation/get_more/result.rb
spec/integration/change_stream_examples_spec.rb
spec/integration/change_stream_spec.rb
spec/mongo/collection/view/change_stream_spec.rb
spec/mongo/cursor_spec.rb

Also includes RUBY-1815 Clarify resume token used in resuming and getResumeToken

RUBY-1708 Support postBatchResumeToken in change streams

---

.evergreen/config.yml

https://jira.mongodb.com/browse/RUBY-1842

RUBY-1842 Test 4.2 server in CI

---

spec/spec_tests/data/transactions/abort.yml
spec/spec_tests/data/transactions/bulk.yml
spec/spec_tests/data/transactions/causal-consistency.yml
spec/spec_tests/data/transactions/commit.yml
spec/spec_tests/data/transactions/count.yml
spec/spec_tests/data/transactions/delete.yml
spec/spec_tests/data/transactions/error-labels.yml
spec/spec_tests/data/transactions/errors-client.yml
spec/spec_tests/data/transactions/errors.yml
spec/spec_tests/data/transactions/findOneAndDelete.yml
spec/spec_tests/data/transactions/findOneAndReplace.yml
spec/spec_tests/data/transactions/findOneAndUpdate.yml
spec/spec_tests/data/transactions/insert.yml
spec/spec_tests/data/transactions/isolation.yml
spec/spec_tests/data/transactions/read-concern.yml
spec/spec_tests/data/transactions/read-pref.yml
spec/spec_tests/data/transactions/reads.yml
spec/spec_tests/data/transactions/retryable-abort.yml
spec/spec_tests/data/transactions/retryable-commit.yml
spec/spec_tests/data/transactions/retryable-writes.yml
spec/spec_tests/data/transactions/run-command.yml
spec/spec_tests/data/transactions/transaction-options.yml
spec/spec_tests/data/transactions/update.yml
spec/support/transactions.rb
spec/support/transactions/test.rb

https://jira.mongodb.com/browse/RUBY-1855

RUBY-1855 Run all transaction tests on sharded clusters

---

lib/mongo/cluster_time.rb
spec/integration/change_stream_examples_spec.rb
spec/integration/server_monitor_spec.rb
spec/integration/server_selector_spec.rb
spec/mongo/client_spec.rb
spec/mongo/cluster_spec.rb
spec/mongo/cluster_time_spec.rb
spec/mongo/collection/view/aggregation_spec.rb
spec/mongo/collection/view/change_stream_spec.rb
spec/mongo/cursor_spec.rb
spec/mongo/server/connection_spec.rb
spec/mongo/server/monitor/connection_spec.rb
spec/mongo/server_spec.rb
spec/mongo/session/session_pool_spec.rb
spec/spec_tests/sdam_monitoring_spec.rb
spec/spec_tests/sdam_spec.rb
spec/support/spec_config.rb

https://jira.mongodb.com/browse/RUBY-1868

RUBY-1868 Further reduce non-determinism in the whole of ruby test suite

---

lib/mongo/bulk_write/transformable.rb
lib/mongo/collection/view/writable.rb
lib/mongo/protocol/update.rb
spec/mongo/bulk_write/ordered_combiner_spec.rb
spec/mongo/bulk_write/unordered_combiner_spec.rb
spec/spec_tests/data/command_monitoring/bulkWrite.yml
spec/spec_tests/data/command_monitoring/updateMany.yml
spec/spec_tests/data/command_monitoring/updateOne.yml
spec/spec_tests/data/transactions/bulk.yml
spec/spec_tests/data/transactions/causal-consistency.yml
spec/spec_tests/data/transactions/update.yml
spec/spec_tests/data/transactions/write-concern.yml

https://jira.mongodb.com/browse/RUBY-1878

RUBY-1878 RUBY-1711 Do not send multi: false & upsert: false to the server

---

docs/reference/driver-compatibility.txt

This is a small addition that updates the compatibility matrix for 2.10

updates mongodb compatibility matrix

---

spec/lite_spec_helper.rb
spec/spec_tests/crud_spec.rb
spec/spec_tests/data/crud_v2/aggregate-out-readConcern.yml
spec/spec_tests/data/crud_v2/bulkWrite-arrayFilters.yml
spec/support/command_monitoring.rb
spec/support/crud.rb
spec/support/crud/operation.rb
spec/support/crud/spec.rb
spec/support/crud/test.rb
spec/support/crud/test_base.rb
spec/support/transactions/operation.rb
spec/support/transactions/spec.rb
spec/support/transactions/test.rb

https://jira.mongodb.com/browse/RUBY-1655

RUBY-1655 Implement CRUD v2 spec tests

---

docs/tutorials/ruby-driver-collations.txt
lib/mongo/bulk_write/transformable.rb
spec/spec_tests/data/crud/write/bulkWrite-arrayFilters.yml
spec/spec_tests/data/crud/write/bulkWrite-collation.yml
spec/spec_tests/data/crud/write/bulkWrite.yml
spec/spec_tests/data/crud/write/insertMany.yml
spec/spec_tests/data/crud/write/updateMany-arrayFilters.yml
spec/spec_tests/data/crud/write/updateOne-arrayFilters.yml
spec/support/crud/operation.rb
spec/support/utils.rb

https://jira.mongodb.com/browse/RUBY-1498

RUBY-1498 Resync CRUD v1 tests for new bulkWrite() tests

---

lib/mongo/client.rb
lib/mongo/collection.rb
lib/mongo/collection/view/builder/aggregation.rb
lib/mongo/collection/view/readable.rb
lib/mongo/database.rb
lib/mongo/database/view.rb
spec/mongo/auth/scram/negotiation_spec.rb
spec/mongo/database_spec.rb
spec/spec_tests/data/crud_v2/db-aggregate.yml
spec/support/authorization.rb
spec/support/client_registry.rb
spec/support/cluster_tools.rb
spec/support/crud/operation.rb
spec/support/crud/test.rb

https://jira.mongodb.com/browse/RUBY-1721

RUBY-1721 Implement database-level aggregation

---

docs/tutorials/ruby-driver-create-client.txt
lib/mongo/uri.rb
spec/mongo/uri_option_parsing_spec.rb
spec/mongo/uri_spec.rb

https://jira.mongodb.com/browse/RUBY-1761

RUBY-1761 URI option fixes

---

lib/mongo/collection/view/aggregation.rb
lib/mongo/collection/view/builder/aggregation.rb
lib/mongo/collection/view/iterable.rb
spec/spec_tests/data/crud_v2/aggregate-merge.yml

https://jira.mongodb.com/browse/RUBY-1836

RUBY-1836 Finer-grained updates from aggregation via $merge

---

spec/integration/connection_spec.rb
spec/integration/sdam_error_handling_spec.rb
spec/mongo/collection/view/map_reduce_spec.rb
spec/mongo/operation/delete/op_msg_spec.rb
spec/mongo/operation/insert/op_msg_spec.rb
spec/mongo/operation/update/op_msg_spec.rb
spec/spec_helper.rb
spec/spec_tests/cmap_spec.rb
spec/support/cluster_config.rb

https://jira.mongodb.com/browse/RUBY-1868

RUBY-1868 actually close local clients after each test

---

lib/mongo/cluster.rb
lib/mongo/srv/monitor.rb
spec/integration/reconnect_spec.rb
spec/integration/srv_monitoring_spec.rb

https://jira.mongodb.com/browse/RUBY-1563

RUBY-1563 Poll SRV records in unknown topologies

---

spec/spec_tests/data/cmap/connection-must-have-id.yml
spec/spec_tests/data/cmap/connection-must-order-ids.yml
spec/spec_tests/data/cmap/pool-checkin-destroy-closed.yml
spec/spec_tests/data/cmap/pool-checkin-destroy-stale.yml
spec/spec_tests/data/cmap/pool-checkin-make-available.yml
spec/spec_tests/data/cmap/pool-checkin.yml
spec/spec_tests/data/cmap/pool-checkout-connection.yml
spec/spec_tests/data/cmap/pool-checkout-error-closed.yml
spec/spec_tests/data/cmap/pool-checkout-multiple.yml
spec/spec_tests/data/cmap/pool-checkout-no-idle.yml
spec/spec_tests/data/cmap/pool-checkout-no-stale.yml
spec/spec_tests/data/cmap/pool-close-destroy-conns.yml
spec/spec_tests/data/cmap/pool-create-max-size.yml
spec/spec_tests/data/cmap/pool-create-min-size.yml
spec/spec_tests/data/cmap/wait-queue-fairness.yml
spec/spec_tests/data/cmap/wait-queue-timeout.yml
spec/support/cmap.rb

https://jira.mongodb.com/browse/RUBY-1936

RUBY-1936 Include address in all cmap spec tests' event assertions

---

lib/mongo/client.rb

Converting boolean if else conditional to ternary operator conditional

Convert if else conditional to ternary for brevity

---

lib/mongo/retryable.rb
spec/integration/retryable_errors_spec.rb
spec/integration/retryable_writes_spec.rb
spec/support/spec_config.rb

https://jira.mongodb.com/browse/RUBY-2004

Fix RUBY-2004 Indicated attempt not always correct

---

docs/tutorials/ruby-driver-authentication.txt
docs/tutorials/user-management.txt
lib/mongo/auth/user.rb
spec/lite_spec_helper.rb
spec/mongo/auth/user/view_spec.rb
spec/mongo/auth/user_spec.rb

https://jira.mongodb.com/browse/RUBY-2055

Fix RUBY-2055 Driver sends null pwd field in createUser when password is not specified

---

lib/mongo/auth/user.rb
lib/mongo/crypt.rb
lib/mongo/crypt/auto_decryption_context.rb
lib/mongo/crypt/binding.rb
spec/mongo/crypt/auto_decryption_context_spec.rb

Create a context object used for auto-decryption.

1924 Auto-decryption Context

---

CONTRIBUTING.md
docs/reference/driver-compatibility.txt

RUBY-2058 add Ruby 2.7 to compatibility tables

---

.evergreen/config.yml
.evergreen/functions.sh
Gemfile
gemfiles/bson_master.gemfile
gemfiles/bson_min.gemfile
gemfiles/standard.rb
lib/mongo/cursor/builder/kill_cursors_command.rb
lib/mongo/cursor/builder/op_kill_cursors.rb
lib/mongo/protocol/serializers.rb
mongo.gemspec
spec/integration/cursor_reaping_spec.rb
spec/mongo/bulk_write_spec.rb
spec/mongo/cursor/builder/op_kill_cursors_spec.rb
spec/runners/command_monitoring.rb
spec/support/utils.rb

RUBY-2059 Depend on bson 4.4.2 for the benefit of driver 2.10

---

.evergreen/config.yml
.evergreen/functions.sh
.evergreen/run-fle-tests.sh
lib/mongo/crypt/auto_encrypter.rb
lib/mongo/crypt/context.rb
lib/mongo/crypt/encrypter.rb
lib/mongo/crypt/encryption_io.rb
spec/mongo/client_auto_encryption_spec.rb
spec/mongo/crypt/data/schema_map.json

This PR implements the methods necessary for auto encryption/decryption and tests those methods.
Upcoming PRs will actually integrate those methods into the required database commands.

RUBY-1934 Auto encryption and decryption unit tests

---

lib/mongo/client.rb

(And clean up existing auto encryption documentation)

RUBY-1922 Add required auto encryption documentation to Client

---

lib/mongo/error/operation_failure.rb
spec/spec_tests/data/retryable_writes/insertOne-serverErrors.yml

[RUBY-2084](https://jira.mongodb.org/browse/RUBY-2084)

RUBY-2084 Make ExceededTimeLimit a RetryableWriteError

---

.evergreen/run-fle-tests.sh
lib/mongo/client_encryption.rb
lib/mongo/crypt/binding.rb
lib/mongo/crypt/data_key_context.rb
lib/mongo/crypt/hooks.rb
spec/mongo/crypt/data_key_context_spec.rb

The second in a series of a few pull requests.

RUBY-2007 Add AWS KMS options to Data Key Context

---

.evergreen/config.yml
spec/README.md
spec/support/crypt.rb
spec/support/spec_config.rb

And update spec README to explain how to run tests with AWS info

RUBY-2007 Move FLE AWS region and key ARN to environment variables for easy customizability

---

lib/mongo/client_encryption.rb
lib/mongo/crypt/binding.rb
lib/mongo/crypt/encryption_io.rb
spec/mongo/client_encryption_spec.rb

* Improve URI parsing
* Do not use the driver-specific implementation of SSL sockets
* Make sure to set nodelay option, perform SNI, and set a timeout
* Improve error handling

RUBY-2007 Clean up SSLSocket usage

---

.dockerignore
.evergreen/.gitignore
.evergreen/Dockerfile.erb
.evergreen/README.md
.evergreen/functions.sh
.evergreen/test-on-docker

https://jira.mongodb.com/browse/RUBY-2135

RUBY-2135 Run evergreen test suite in docker

---

lib/mongo/client_encryption.rb
lib/mongo/crypt/explicit_encryption_context.rb
spec/mongo/client_encryption_spec.rb
spec/mongo/crypt/explicit_encryption_context_spec.rb
spec/support/crypt.rb
spec/support/crypt/data_keys/key_document_aws.json
spec/support/crypt/data_keys/key_document_local.json

Changes to integration test coming in follow-up PR.

RUBY-2008 Support key_alt_name option for explicit encryption

---

.evergreen/run-tests-mlaunch.sh

The changes in this PR cover evergreen scripts, as opposed to docker scripts and evergreen config. These changes are eventually going to be used by existing evergreen configurations.

RUBY-2135 mlaunch changes to support docker work

---

lib/mongo/crypt/context.rb
spec/integration/auto_encryption_spec.rb

Including a test that fails before this change was made and and now passes.

RUBY-2133 Fix need_mongo_collinfo state

---

.evergreen/Dockerfile.erb
.evergreen/README.md
.evergreen/functions.sh
.evergreen/get-mongodb-download-url
.evergreen/run-fle-tests.sh
.evergreen/run-local-tls-tests.sh
.evergreen/run-tests-mlaunch.sh
.evergreen/run-x509-tests.sh
.evergreen/test-on-docker
.evergreen/tools.rb

https://jira.mongodb.com/browse/RUBY-2135

RUBY-2135 improve efficiency of testing on docker, add more configurations

---

.evergreen/Dockerfile.erb
.evergreen/config.yml
.evergreen/functions.sh
.evergreen/run-tests-mlaunch.sh
.evergreen/run-x509-tests.sh
.evergreen/test-on-docker
spec/support/spec_config.rb

https://jira.mongodb.com/browse/RUBY-2135

RUBY-2135 assorted docker-related improvements

---

lib/mongo/collection/view/builder/find_command.rb
spec/mongo/collection/view/builder/find_command_spec.rb

https://jira.mongodb.com/browse/RUBY-2079

RUBY-2079 Deprecate oplogReplay find command option from CRUD spec

---

docs/tutorials/client-side-encryption.txt
lib/mongo/client_encryption.rb

Also, fix some errors in the `ClientEncryption` docstrings.

RUBY-2042 Add Explicit Encryption tutorial

---

docs/tutorials/client-side-encryption.txt

Documentation for:
* creating a master key with AWS and local
* creating a data key with AWS and local
* creating a schema map and reading it with `BSON::ExtJson#parse`

RUBY-2042 Additions to FLE Documentation

---

.evergreen/config.yml
gemfiles/bson_min.gemfile
mongo.gemspec
spec/mongo/client_encryption_spec.rb

https://jira.mongodb.com/browse/RUBY-2080

RUBY-2080 Test FLE on jruby

---

lib/mongo/crypt/encryption_io.rb
spec/mongo/crypt/encryption_io_spec.rb

https://jira.mongodb.com/browse/RUBY-2034

RUBY-2034 Improve security of mongocryptd spawning

---

spec/mongo/auth/scram/conversation_spec.rb
spec/mongo/auth/scram/negotiation_spec.rb
spec/support/utils.rb

This primarily adds the scopes around assertions and removes retry attempts. The assertions seem to be passing with a higher success rate.

try to fix intermittent failures on jruby

---

gemfiles/bson_min.gemfile
mongo.gemspec
spec/integration/client_side_encryption/corpus_spec.rb

https://jira.mongodb.com/browse/RUBY-2152

RUBY-2152 bump bson dependency to 4.8.2, remove workarounds

---

lib/mongo/address.rb
lib/mongo/server/connection.rb
lib/mongo/server/monitor/connection.rb
spec/integration/connection_spec.rb
spec/mongo/address_spec.rb
spec/mongo/server/connection_spec.rb
spec/mongo/server/monitor/connection_spec.rb
spec/mongo/socket/ssl_spec.rb
spec/mongo/socket/tcp_spec.rb

https://jira.mongodb.com/browse/RUBY-2144

Fix RUBY-2144 Redundant socket connections during address resolution

---

docs/tutorials/ruby-driver-create-client.txt
lib/mongo/address.rb
lib/mongo/socket.rb
lib/mongo/socket/ssl.rb
lib/mongo/socket/tcp.rb
spec/integration/connection_spec.rb
spec/mongo/socket_spec.rb

https://jira.mongodb.com/browse/RUBY-2162

RUBY-2162 Close sockets when connections fail

---

.dockerignore
.evergreen/Dockerfile.erb
.evergreen/README.md
.evergreen/config.yml
.evergreen/run-tests-enterprise-auth.sh
.evergreen/run-tests-kerberos-unit.sh
.evergreen/run-tests.sh
.evergreen/test-on-docker
.gitignore
gemfiles/mongo_kerberos.gemfile
spec/enterprise_auth/kerberos_spec.rb

- Apply FLE credential storage system to kerberos credentials
- Move kerberos init into a shell script so that it can be invoked in docker

Dockerize enterprise auth tests

---

.evergreen/config.yml
.evergreen/test-on-docker

- Fix docker orchestrator when no private variables are defined
- Add evergreen configurations to test docker orchestrator in evergreen

Fix docker orchestrator

---

spec/spec_tests/data/sdam/single/direct_connection_wrong_set_name.yml
spec/spec_tests/data/uri_options/connection-options.yml

https://jira.mongodb.com/browse/RUBY-2126

RUBY-2126 remaining test changes per spec PR review

---

.evergreen/Dockerfile.erb
.evergreen/functions-kerberos.sh
.evergreen/local-kerberos/Dockerfile
.evergreen/local-kerberos/README.md
.evergreen/local-kerberos/entrypoint.sh
.evergreen/run-tests-kerberos-integration.sh
.evergreen/test-on-docker
spec/README.md
spec/kerberos/kerberos_spec.rb

https://jira.mongodb.com/browse/RUBY-2196

RUBY-2196 finish local kerberos instructions and Docker configuration

---

docs/includes/unicode-nbsp.rst
docs/reference/driver-compatibility.txt
docs/tutorials/ruby-driver-authentication.txt

https://jira.mongodb.com/browse/RUBY-1552

RUBY-1552 Document Ruby Kerberos usage

---

.evergreen/aws
.evergreen/functions.sh
.evergreen/provision-docker
.evergreen/provision-local
.evergreen/provision-remote
.evergreen/test-remote
spec/NOTES.aws-auth.md
spec/support/aws_utils.rb
spec/support/aws_utils/inspector.rb
spec/support/aws_utils/orchestrator.rb
spec/support/aws_utils/provisioner.rb

https://jira.mongodb.com/browse/RUBY-1999

RUBY-1999 provisioning and tooling changes to support testing ecs in evergreen

---

.evergreen/aws
.evergreen/config.yml
.evergreen/lib/ecs_setup.rb
.evergreen/run-tests-atlas.sh
.evergreen/run-tests-aws-auth.sh
.evergreen/run-tests-ecs.sh
.evergreen/run-tests-kerberos-integration.sh
.evergreen/run-tests-kerberos-unit.sh
.evergreen/run-tests.sh
lib/mongo/auth/aws/credentials_retriever.rb
spec/NOTES.aws-auth.md
spec/README.aws-auth.md
spec/integration/aws_credentials_retriever_spec.rb
spec/support/aws_utils/base.rb
spec/support/aws_utils/orchestrator.rb

https://jira.mongodb.com/browse/RUBY-1999

RUBY-1999 credentials retrieval from ECS task metadata

---

lib/mongo/server/monitor.rb
lib/mongo/server/pending_connection.rb
lib/mongo/server/round_trip_time_averager.rb
spec/mongo/server/round_trip_time_averager_spec.rb

- Use the entire heartbeat duration (connection+tls handshake+ismaster)
for heartbeat events
- Simplify rtt averaging code

RUBY-2132 refactor rtt calculations

---

lib/mongo/server/monitor.rb
lib/mongo/server/monitor/connection.rb
spec/support/background_thread_registry.rb

RUBY-2132 misc cleanup

---

lib/mongo/address.rb
lib/mongo/crypt/encryption_io.rb
lib/mongo/server/connection.rb
lib/mongo/server/monitor/connection.rb
lib/mongo/socket.rb
lib/mongo/socket/ssl.rb
lib/mongo/socket/tcp.rb
lib/mongo/socket/unix.rb
spec/mongo/socket/ssl_spec.rb
spec/mongo/socket/tcp_spec.rb
spec/mongo/socket/unix_spec.rb
spec/mongo/socket_spec.rb

RUBY-2132 add address, connection generation & monitoring flag fields to sockets for diagnostics

---

spec/spec_tests/data/max_staleness/ReplicaSetNoPrimary/MaxStalenessTooSmall.yml

Added tests as per the specification, didn't need to change any code as the tests passed.

RUBY-2276 Added coverage for valid maxStalenessSeconds with no viable servers

---

lib/mongo/socket/ssl.rb
lib/mongo/socket/tcp.rb

I couldn't figure out how to test for this reliably. I tried to set the timeout duration from the test but ultimately it didn't work...

RUBY-1657 added error message to timeouts

---

spec/integration/change_stream_examples_spec.rb

I couldn't get the code to run on my local machine but I used the same syntax as what was there before and just modified the variable names/pipeline object, so it should be fine.

RUBY-1413 modified Change Stream Example 4

---

spec/support/child_process_helper.rb
spec/support/spec_organizer.rb

https://jira.mongodb.com/browse/RUBY-2313

RUBY-2313 test bucketing improvements

---

lib/mongo/protocol/msg.rb
spec/mongo/protocol/msg_spec.rb

RUBY-2132 exhaust flag & unit tests

---

docs/tutorials/ruby-driver-create-client.txt

RUBY-2323 there is no default socket timeout

---

lib/mongo/logger.rb
spec/mongo/logger_spec.rb

https://jira.mongodb.com/browse/RUBY-2356

RUBY-2356 Set default logger level to info

---

spec/mongo/uri_spec.rb
spec/runners/connection_string.rb
spec/spec_tests/uri_options_spec.rb

https://jira.mongodb.com/browse/RUBY-2358

RUBY-2358 fix kerberos unit & spec tests

---

.evergreen/config-atlas.yml
.evergreen/config.yml
.evergreen/config/axes.yml.erb
.evergreen/config/common.yml.erb
.evergreen/config/standard.yml.erb
.evergreen/functions-config.sh
.evergreen/run-tests.sh
spec/README.md
spec/integration/ocsp_connectivity_spec.rb
spec/support/lite_constraints.rb
spec/support/spec_config.rb

https://jira.mongodb.com/browse/RUBY-2400

RUBY-2400 Add OCSP + insecure configurations to Evergreen

---

lib/mongo/collection.rb
lib/mongo/collection/view/iterable.rb
lib/mongo/collection/view/readable.rb
lib/mongo/query_cache.rb
spec/integration/query_cache_spec.rb
spec/mongo/query_cache_spec.rb

https://jira.mongodb.com/browse/RUBY-2130

RUBY-2130 misc query cache changes

---

.evergreen/lib/server_setup.rb
.evergreen/run-tests-aws-auth.sh
.evergreen/run-tests.sh
lib/mongo/client.rb
spec/NOTES.aws-auth.md
spec/integration/client_authentication_options_spec.rb
spec/integration/connection_pool_populator_spec.rb
spec/mongo/client_construction_spec.rb
spec/mongo/server/connection_pool_spec.rb
spec/mongo/server/connection_spec.rb
spec/runners/auth.rb
spec/spec_tests/cmap_spec.rb
spec/support/client_registry_macros.rb

https://jira.mongodb.com/browse/RUBY-2421

Fix RUBY-2421 Auth mechanism properties not downcased when client is created with host and Ruby options with symbol key

---

lib/mongo/cursor.rb
lib/mongo/operation/find/result.rb
spec/mongo/query_cache_spec.rb

I have manually tested this code against an Atlas Data Lake instance, and in a PR for RUBY-2325, I will set up our test suite to run with Data Lake.

RUBY-2211 Use namespace returned from find command in getMore

---

spec/mongo/socket/ssl_spec.rb

https://jira.mongodb.com/browse/RUBY-1387

RUBY-1387 fix test suite configurations

---

Rakefile
lib/mongo/session.rb
spec/integration/transactions_examples_spec.rb

https://jira.mongodb.com/browse/RUBY-2447

RUBY-2447 Fix intermittent transaction examples test failures

---

spec/integration/sdam_error_handling_spec.rb
spec/integration/sdam_events_spec.rb

https://jira.mongodb.org/browse/RUBY-2446

RUBY-2446 Fix intermittent SDAM test failures

---

.evergreen/config.yml
.evergreen/config/standard.yml.erb
spec/integration/ocsp_verifier_spec.rb
spec/mongo/socket/ssl_spec.rb
spec/support/common_shortcuts.rb

https://jira.mongodb.com/browse/RUBY-2448

RUBY-2448 Fix OCSP test failures

---

lib/mongo/cluster.rb
lib/mongo/socket.rb
spec/integration/ocsp_verifier_spec.rb
spec/lite_spec_helper.rb
spec/mongo/server/connection_pool/populator_spec.rb
spec/mongo/socket_spec.rb
spec/support/utils.rb

https://jira.mongodb.com/browse/RUBY-2456

RUBY-2456 Fix timeouts on JRuby

---

lib/mongo/cluster/sdam_flow.rb
spec/mongo/cluster_spec.rb

https://jira.mongodb.com/browse/RUBY-2457

RUBY-2457 Fix single topology errors

---

spec/runners/unified.rb
spec/runners/unified/assertions.rb
spec/runners/unified/crud_operations.rb
spec/runners/unified/ddl_operations.rb
spec/runners/unified/entity_map.rb
spec/runners/unified/error.rb
spec/runners/unified/event_subscriber.rb
spec/runners/unified/exceptions.rb
spec/runners/unified/grid_fs_operations.rb
spec/runners/unified/support_operations.rb
spec/runners/unified/test.rb
spec/runners/unified/test_group.rb

https://jira.mongodb.com/browse/RUBY-2484

RUBY-2484 Update unified test runner for integration with drivers-atlas-testing

---

lib/mongo/auth/aws/conversation.rb
lib/mongo/auth/conversation_base.rb
lib/mongo/auth/cr/conversation.rb
lib/mongo/auth/gssapi/conversation.rb
lib/mongo/auth/ldap/conversation.rb
lib/mongo/auth/sasl_conversation_base.rb
lib/mongo/auth/scram_conversation_base.rb
lib/mongo/auth/x509/conversation.rb
spec/mongo/auth/ldap/conversation_spec.rb
spec/mongo/auth/ldap_spec.rb
spec/mongo/auth/x509/conversation_spec.rb

https://jira.mongodb.com/browse/RUBY-2429

RUBY-2550 unify protocol message construction in auth code

---

docs/index.txt
docs/installation.txt
docs/reference/authentication.txt
docs/reference/create-client.txt
docs/reference/monitoring.txt
docs/release-notes.txt

Rendered: https://p-mongo.github.io/rendered-docs/driver/tutorial/release-notes.html

Add release notes to driver documentation

---

.evergreen/config-atlas.yml
.evergreen/config.yml
.evergreen/config/axes.yml.erb
.evergreen/config/common.yml.erb
.evergreen/config/standard.yml.erb
.evergreen/run-tests-docker.sh
.evergreen/update-evergreen-configs
gemfiles/standard.rb
lib/mongo/socket/ocsp_verifier.rb
spec/integration/ocsp_verifier_spec.rb
spec/support/certificates/README.md
spec/support/certificates/atlas-ocsp-ca.crt
spec/support/certificates/atlas-ocsp.crt
spec/support/common_shortcuts.rb

https://jira.mongodb.com/browse/RUBY-2615

RUBY-2615 update expired certificate & run ocsp verifier tests in docker

---

.evergreen/config-atlas.yml
.evergreen/config.yml
.evergreen/config/axes.yml.erb
.evergreen/config/standard.yml.erb
spec/spec_tests/data/sdam_integration/hello-timeout.yml

https://jira.mongodb.org/browse/RUBY-2758

RUBY-2578 Disable Ubuntu 14.04 based configs

---

.evergreen/config-atlas.yml
.evergreen/config.yml
.evergreen/config/axes.yml.erb
.evergreen/config/standard.yml.erb
spec/spec_tests/data/sdam_integration/hello-timeout.yml

Reverts mongodb/mongo-ruby-driver#2320

RUBY-2578 Repair Ubuntu 14.04 based configs

---

spec/mongo/client_spec.rb

RUBY-2924 Improve implicit session usage tests

---

spec/runners/unified/crud_operations.rb
spec/spec_tests/data/crud_unified/aggregate-allowdiskuse.yml
spec/spec_tests/data/crud_v2/find-allowdiskuse.yml

RUBY-2956 Make allowDiskUse opt-out rather  than opt-in in 6.0

---

docs/reference/query-cache.txt
lib/mongo/query_cache.rb

Fixes MONGOID-4990
I'm not sure the best way to test this. We could use mocks? I don't think we want to require Rails into the test suite...

RUBY-2966 Add ActiveJob middleware for query cache.

---

profile/benchmarking/parallel.rb
profile/benchmarking/single_doc.rb

RUBY-2998 update benchmark suite and verify it still works

---

lib/mongo/bulk_write.rb
lib/mongo/collection/view/writable.rb
lib/mongo/error/invalid_replacement_document.rb
lib/mongo/error/invalid_update_document.rb
lib/mongo/operation/update.rb
spec/integration/query_cache_spec.rb
spec/integration/retryable_writes/retryable_writes_36_and_older_spec.rb
spec/integration/size_limit_spec.rb
spec/mongo/client_spec.rb
spec/mongo/collection_crud_spec.rb
spec/spec_tests/data/crud_unified/bulkWrite-update-validation.yml
spec/spec_tests/data/crud_unified/replaceOne-validation.yml
spec/spec_tests/data/crud_unified/updateMany-validation.yml
spec/spec_tests/data/crud_unified/updateOne-validation.yml
spec/spec_tests/data/transactions/errors-client.yml
spec/spec_tests/data/unified/valid-pass/poc-transactions.yml

The CI failures all look unrelated and additionally they come up on other PRs.

RUBY-2996 Implement update and replace validation

---

docs/reference/create-client.txt
lib/mongo/client.rb
lib/mongo/server/connection_pool.rb
spec/mongo/client_construction_spec.rb
spec/mongo/server/connection_pool_spec.rb

https://jira.mongodb.org/browse/RUBY-3010
https://jira.mongodb.org/browse/RUBY-3011

RUBY-3010 Allow unlimited connection pool

---

lib/mongo/index/view.rb
spec/integration/docs_examples_spec.rb
spec/mongo/index/view_spec.rb

https://jira.mongodb.org/browse/RUBY-3037

RUBY-3037: Support index wildcard_projection option

---

docs/reference/client-side-encryption.txt
gemfiles/standard.rb
lib/mongo/client_encryption.rb
lib/mongo/crypt/explicit_encrypter.rb
lib/mongo/crypt/rewrap_many_data_key_result.rb
spec/integration/client_side_encryption/explicit_queryable_encryption_spec.rb
spec/integration/client_side_encryption/unique_index_on_key_alt_names_prose_spec.rb
spec/mongo/crypt/explicit_encryption_context_spec.rb
spec/runners/crud/requirement.rb
spec/runners/unified/client_side_encryption_operations.rb
spec/spec_tests/data/client_side_encryption/fle2-Delete.yml
spec/spec_tests/data/client_side_encryption/fle2-EncryptedFields-vs-jsonSchema.yml
spec/spec_tests/data/client_side_encryption/fle2-FindOneAndUpdate.yml
spec/spec_tests/data/client_side_encryption/fle2-InsertFind-Indexed.yml
spec/spec_tests/data/client_side_encryption/fle2-Update.yml
spec/spec_tests/data/client_side_encryption/unified/addKeyAltName.yml
spec/spec_tests/data/client_side_encryption/unified/createDataKey-kms_providers-invalid.yml
spec/spec_tests/data/client_side_encryption/unified/createDataKey.yml
spec/spec_tests/data/client_side_encryption/unified/deleteKey.yml
spec/spec_tests/data/client_side_encryption/unified/getKey.yml
spec/spec_tests/data/client_side_encryption/unified/getKeyByAltName.yml
spec/spec_tests/data/client_side_encryption/unified/getKeys.yml
spec/spec_tests/data/client_side_encryption/unified/removeKeyAltName.yml
spec/spec_tests/data/client_side_encryption/unified/rewrapManyDataKey.yml

https://jira.mongodb.org/browse/RUBY-3030
https://jira.mongodb.org/browse/RUBY-3031
https://jira.mongodb.org/browse/RUBY-3034
https://jira.mongodb.org/browse/RUBY-3039
https://jira.mongodb.org/browse/RUBY-3040
https://jira.mongodb.org/browse/RUBY-3042
https://jira.mongodb.org/browse/RUBY-3043

RUBY-3031 Update expected FLE 2 find payloads

---

lib/mongo/client.rb
lib/mongo/error/invalid_read_option.rb
spec/mongo/client_construction_spec.rb

Is this what you had in mind with this ticket?

RUBY-1595 Improve error reporting when symbol/string is passed as read preference

---

docs/reference/monitoring.txt

Is this what you had in mind @p-mongo?

RUBY-1554 Mention to_json in logging examples in tutorial

---

spec/runners/unified/crud_operations.rb
spec/runners/unified/ddl_operations.rb
spec/runners/unified/test.rb
spec/spec_tests/data/crud_unified/aggregate-merge-errorResponse.yml
spec/spec_tests/data/crud_unified/bulkWrite-errorResponse.yml
spec/spec_tests/data/crud_unified/deleteOne-errorResponse.yml
spec/spec_tests/data/crud_unified/findOneAndUpdate-errorResponse.yml
spec/spec_tests/data/crud_unified/insertOne-errorResponse.yml
spec/spec_tests/data/crud_unified/updateOne-errorResponse.yml
spec/spec_tests/data/unified/valid-pass/expectedError-errorResponse.yml

RUBY-3049 Provide access to raw result document when the server returns an error for a command

---

spec/spec_tests/data/sessions_unified/implicit-sessions-default-causal-consistency.yml

RUBY-3058. Looks like these tests work with the current driver.

RUBY-3058 sync causal consistency test

---

lib/mongo/cluster.rb
lib/mongo/server_selector/base.rb
spec/integration/sdam_error_handling_spec.rb

RUBY-2492 Test that clients wait 500ms between failed isMaster checks

---

lib/mongo/retryable.rb

This adds a new private method, `retryable_exceptions`, that enumerates those exceptions that are (in most cases) retryable. The method then replaces the explicit lists of exceptions in various rescue statements.
~I also noticed multiple instances of duplication in the code and took the opportunity to try and tidy that up, but realized as I was doing so that this probably expands the scope of the ticket unnecessarily. I can back those changes out if needed and resubmit the refactoring as a separate PR.~
I removed the other refactorings from the original PR and will resubmit them separately.

RUBY-3191 Abstract retryability of errors

---

.evergreen/config.yml
.evergreen/config/standard.yml.erb
.evergreen/run-tests-serverless.sh
.evergreen/run-tests.sh
spec/mongo/index/view_spec.rb

This PR is according to https://github.com/mongodb-labs/drivers-evergreen-tools/pull/263
It also fixes some other build failures.

Fix KMIP test setup

---

.evergreen/config.yml
.evergreen/config/common.yml.erb
.evergreen/config/standard.yml.erb
.evergreen/run-tests.sh
spec/mongo/collection_ddl_spec.rb

This PR adds missing test configuration for FLE on latest, and also fixes some repeating test failures. Unfortunately, there are still some flaky tests.

Fix failures on latest

---

spec/spec_tests/data/command_monitoring_unified/writeConcernError.yml

Adds the new spec test, which passes without any other changes.

RUBY-3203 Add a test for CommandSucceededEvent

---

.evergreen/config.yml
.evergreen/config/axes.yml.erb
.evergreen/config/common.yml.erb
.evergreen/run-tests.sh
spec/integration/fork_reconnect_spec.rb
spec/spec_tests/client_side_encryption_spec.rb
spec/spec_tests/client_side_encryption_unified_spec.rb
spec/support/spec_config.rb
spec/support/utils.rb

Spec compliance: make sure tests are run against both mongocryptd and crypt_shared.

RUBY-3154 Test crypt_shared with older server versions

---

.evergreen/config.yml
.evergreen/config/axes.yml.erb
.evergreen/config/standard.yml.erb
spec/integration/client_update_spec.rb
spec/integration/query_cache_spec.rb
spec/integration/snapshot_query_examples_spec.rb
spec/support/common_shortcuts.rb

https://jira.mongodb.org/browse/RUBY-3246
https://jira.mongodb.org/browse/RUBY-3264
https://jira.mongodb.org/browse/RUBY-3265

RUBY-3246 Test against 7.0

---

spec/spec_tests/data/client_side_encryption/explain.yml

https://jira.mongodb.org/browse/RUBY-3279

RUBY-3279 Bump min server version for FLE test

---

lib/mongo/collection/view.rb
lib/mongo/collection/view/iterable.rb
spec/integration/find_options_spec.rb

* RUBY-3332 Fix tailable cursors
* Extract method
* Fix code review remarks

RUBY-3332 Fix tailable cursors (#2793)

---

lib/mongo/collection/view.rb
lib/mongo/collection/view/iterable.rb
spec/integration/find_options_spec.rb

* RUBY-3332 Fix tailable cursors
* Extract method
* Fix code review remarks

RUBY-3332 Fix tailable cursors

---

spec/spec_tests/data/load_balancers/cursors.yml
spec/spec_tests/data/load_balancers/sdam-error-handling.yml
spec/spec_tests/data/load_balancers/transactions.yml
spec/spec_tests/data/load_balancers/wait-queue-timeouts.yml

Most of these are skipped until we properly implement the load-balancer spec.

RUBY-2881 add missing LB tests

---

.gitmodules

Use the new toolchain builds for running tests.

RUBY-3598 Update spec/shared submodule for new toolchain
