mongodb/mongo-ruby-driver

- spec/mongo/client_spec.rb
- spec/spec_helper.rb
- spec/support/authorization.rb
I'm setting up jenkins to run our specs on different topologies so I've added some places where we consider env variables.
> Consider env variables so test suite can run with other topologies

- lib/mongo.rb
- lib/mongo/connection/node.rb
- test/helpers/test_unit.rb
- test/replica_set/basic_test.rb
Support for detecting when a socket was established in a different process and automatically discarding it was added to this driver in 997d9b8ae2f5f391ef23dc4d3792e7d863675eb8, and refined in a393557eeb8c1a9a049f4d289be51e50579ebf40.
Instances of the Node class maintain their own sockets for refreshing replica set data; they need to be protected from reuse in the same way.
> Avoid sharing sockets between forked processes

- lib/mongo/cluster.rb
- lib/mongo/cluster/topology/single.rb
- lib/mongo/operation/read_preferrable.rb
- lib/mongo/server.rb
- lib/mongo/server/context.rb
- spec/support/shared/operation.rb
Allow Single Topology type to return all servers not Unknown.
Always set the slaveOk bit for queries sent in a Single Topology if read preference is not set and the server is not a mongos.
> RUBY-891 Single topology type servers and slaveOk bit

- lib/mongo/protocol/query.rb
- spec/mongo/protocol/query_spec.rb
I guessed that 250 characters was a decent limit on the selector field when logging an error with a query but am open to suggestions for that limit to be decreased or increased.
> RUBY-897 Print first 250 chars of query selector when logging and rescue inspect error

- lib/mongo/bulk_write/bulk_writable.rb
- lib/mongo/bulk_write/deletable.rb
- lib/mongo/bulk_write/insertable.rb
- lib/mongo/grid/fs.rb
- spec/mongo/grid/fs_spec.rb
by using the bulk write API
todo: what is the expected return value from inserting to gridfs?
> RUBY-946 Account for max bson size when inserting GridFS file chunks

- lib/mongo/socket.rb
- lib/mongo/socket/ssl.rb
- spec/mongo/socket/ssl_spec.rb
- spec/spec_helper.rb
These changes get our tests working on SSL again.
> Fix socket references

- lib/mongo/bulk_write.rb
- lib/mongo/bulk_write/bulk_writable.rb
- lib/mongo/bulk_write/deletable.rb
- lib/mongo/bulk_write/insertable.rb
- lib/mongo/bulk_write/ordered_bulk_write.rb
- lib/mongo/bulk_write/result.rb
- lib/mongo/bulk_write/unordered_bulk_write.rb
- lib/mongo/collection.rb
- lib/mongo/error.rb
- lib/mongo/operation/write/bulk/bulk_mergable.rb
- lib/mongo/operation/write/bulk/bulk_update/result.rb
- spec/mongo/bulk_write_spec.rb
- spec/mongo/collection_spec.rb
- spec/support/shared/bulk_write.rb
This makes the bulk write result now a proper `Result` object according to the CRUD spec and allows for the inserted and upserted document ids to be preset. This also instroduces constants for most of the bulk write fields being utilized.
This also addresses RUBY-946 on master as `insert_many` now delegates to the bulk API.
> Refactor bulk write to match CRUD spec

- lib/mongo/auth/cr/conversation.rb
- lib/mongo/error/invalid_bulk_operation.rb
- lib/mongo/operation/aggregate.rb
- lib/mongo/operation/command.rb
- lib/mongo/operation/kill_cursors.rb
- lib/mongo/operation/map_reduce.rb
- lib/mongo/operation/read/collections_info.rb
- lib/mongo/operation/read/get_more.rb
- lib/mongo/operation/read/indexes.rb
- lib/mongo/operation/read/list_collections.rb
- lib/mongo/operation/read/list_indexes.rb
- lib/mongo/operation/read/query.rb
- lib/mongo/operation/write/bulk/bulk_delete.rb
- lib/mongo/operation/write/bulk/bulk_insert.rb
- lib/mongo/operation/write/bulk/bulk_insert/result.rb
- lib/mongo/operation/write/bulk/bulk_update.rb
- lib/mongo/operation/write/create_index.rb
- lib/mongo/operation/write/create_user.rb
- lib/mongo/operation/write/delete.rb
- lib/mongo/operation/write/drop_index.rb
- lib/mongo/operation/write/insert.rb
- lib/mongo/operation/write/insert/result.rb
- lib/mongo/operation/write/remove_user.rb
- lib/mongo/operation/write/update.rb
- lib/mongo/operation/write/update_user.rb
Some doc pages weren't being generated because of errors. These changes fix the errors. 
For example, this redirects to the main page:
http://api.mongodb.org/ruby/current/Mongo/Operation/Write/BulkUpdate.html
> Documentation updates for yard doc errors

- lib/mongo/cluster.rb
- lib/mongo/cluster/topology.rb
- lib/mongo/cluster/topology/replica_set.rb
- lib/mongo/cluster/topology/sharded.rb
- lib/mongo/cluster/topology/single.rb
- lib/mongo/cluster/topology/unknown.rb
- lib/mongo/event.rb
- lib/mongo/event/standalone_discovered.rb
- lib/mongo/server/description/inspector.rb
- lib/mongo/server/description/inspector/standalone_discovered.rb
- spec/mongo/cluster/topology_spec.rb
- spec/mongo/server_discovery_and_monitoring_spec.rb
- spec/support/sdam/sharded/single_mongos.yml
This pull request adds a StandaloneDiscovered event and always sets a topology to Unknown if :connect is not explicitly specified.
This will allow a Cluster Topology to be set to Sharded in the case that a single mongos is discovered.
> RUBY-949 Initialize topologies to Unknown and discover standalones

- lib/mongo/client.rb
- lib/mongo/cluster.rb
- lib/mongo/collection/view/aggregation.rb
- lib/mongo/collection/view/map_reduce.rb
- lib/mongo/database.rb
- lib/mongo/server_selector.rb
- lib/mongo/server_selector/selectable.rb
- spec/mongo/server_selection_spec.rb
- spec/mongo/server_selector/nearest_spec.rb
- spec/mongo/server_selector/primary_preferred_spec.rb
- spec/mongo/server_selector/primary_spec.rb
- spec/mongo/server_selector/secondary_preferred_spec.rb
- spec/mongo/server_selector/secondary_spec.rb
- spec/mongo/server_selector_spec.rb
- spec/support/shared/server_selector.rb
I changed the API of ServerSelector to make it simpler. It was awkward by having multiple arguments and was preventing me from easily creating a ServerSelector object in the GridFS refactor.
> ServerSelector refactor

- lib/mongo/address.rb
- spec/mongo/address_spec.rb
Prior to this change, if the provided server address resolved to IPv6
but the mongo server wasn't configured for IPv6, the client would
continuously attempt to connect  to the IPv6 address until the
server_selection_timeout was hit and never fallback to IPv4.
This fixes the behavior to try all the different protocol families in
the list.
Fixes https://jira.mongodb.org/browse/RUBY-986.
> RUBY-986 Fallback to IPv4 if IPv6 isn't supported

- lib/mongo/address.rb
- lib/mongo/address/unix.rb
- lib/mongo/socket.rb
- lib/mongo/socket/unix.rb
- spec/mongo/address/unix_spec.rb
- spec/mongo/socket/unix_spec.rb
This is an initial take on supporting Unix domain sockets.
Although with this patch the driver seems to work fine with unix sockets, it's far from complete. However I can go on and work on it if it's on the right track.
What do you think?
> RUBY-981: Add support for Unix domain sockets

- lib/mongo/client.rb
- spec/mongo/client_spec.rb
Hi,
I'd like to use `collections` as an instance method of `Mongo::Client`.
The use-case example is [here](https://github.com/padrino/padrino-framework/blob/592fd760619ba86af1c4de5fa0b3f5170c418ab1/padrino-gen/lib/padrino-gen/padrino-tasks/mongoid.rb#L6-L60).
Thanks.
> Delegate collections to the current database

- lib/mongo/retryable.rb
Graceful stepdowns and `kill -9` of mongod primaries now work great in my setup, you just need to update this. :grin:
> max_read_retries and read_retry_interval are methods on Cluster.

- lib/mongo/client.rb
- lib/mongo/cluster.rb
- lib/mongo/error/operation_failure.rb
- lib/mongo/retryable.rb
- spec/mongo/retryable_spec.rb
This adds additional read retry scenarios on `OperationFailure`s coming from a mongos only. This is because the `ping` that is executed against a running mongos always returns ready no matter what the state of the cluster behind it is, and the normal server selection/socket retry will not cover this scenario.
1. Adds a `max_read_retries` configuration option that is only applicable to sharded clusters when specific `OperationFailure`s are raised.
2. Adds a `read_retry_interval` configuration option to set the wait time between retries.
Note that we can only look at the error messages themselves, and not the codes. The codes have changed between server versions and some are not relevant to the same scenario anymore, such as the commented 15988 - which was previously an "error querying …
> Retry on mongos operation failures

- lib/mongo/retryable.rb
- spec/mongo/retryable_spec.rb
@durran quick logic fix for https://github.com/mongodb/mongo-ruby-driver/pull/692.
> Only retry max_read_retries times, not infinitely.

- lib/mongo/socket/ssl.rb
- spec/mongo/socket/ssl_spec.rb
[IO#readbyte](http://docs.rubydocs.org/ruby-2-2-3/Ruby%202.2.3/classes/IO.html#method-i-readbyte) – and thus [Mongo::Socket#readbyte](https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/socket.rb#L143) – behave as follows:
1. Return the next 8-bit byte (0..255) as an Integer if data is present.
2. Raise EOFError if EOF was reached before then.
[Mongo::Socket::SSL overrides this](https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/socket/ssl.rb#L95) to simply call [OpenSSL::Buffering](http://docs.rubydocs.org/ruby-2-2-3/Ruby%202.2.3/classes/OpenSSL/Buffering.html#method-i-read) resp. [IO#read](http://docs.rubydocs.org/ruby-2-2-3/Ruby%202.2.3/classes/IO.html#method-i-read) which behave markedly different:
1. Return the String representation of the first 8-bit …
> Bring Socket::SSL#readbyte in line with Socket / IO#readbyte

- lib/mongo/operation/executable.rb
By using const_defined? instead of defined, we can restrict the searching for Result class under current namespace.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb/mongo-ruby-driver/703)
> Fix RUBY-1051: fails if exists a toplevel Result class

- mongo.gemspec
Rubyforge isn't used anymore, it has been replaced by Rubygems.org
> Remove Rubyforge project from gemspec

- lib/mongo/db.rb
- Added documentation to db.eval
> RUBY-1009 - Deprecate eval helpers

- lib/mongo/collection.rb
- lib/mongo/collection/view/writable.rb
- spec/mongo/collection_spec.rb
- Added write_concern option to find_one_and_delete, find_one_and_replace, find_one_and_update.
> RUBY-1037 - Support sending write concern to findAndModify commands

- lib/mongo/collection/view/readable.rb
- lib/mongo/cursor/builder/get_more_command.rb
- spec/mongo/cursor/builder/get_more_command_spec.rb
- Add the ability to add the option in the view fluid interface.
- Adds maxTimeMS to the getmore command is maxAwaitTimeMS is set as an
option.
- Ignores the option in all other cases.
> RUBY-1064: Add maxAwaitTimeMS

- lib/mongo/utils/core_ext.rb
Don't override ActiveSupport assert_valid_keys if defined
See https://jira.mongodb.org/browse/RUBY-1066
> RUBY-1066 Don't override previously-defined Hash#assert_valid_keys

- lib/mongo/cluster.rb
- lib/mongo/collection/view/aggregation.rb
- lib/mongo/collection/view/iterable.rb
- lib/mongo/collection/view/map_reduce.rb
- lib/mongo/collection/view/readable.rb
- lib/mongo/database.rb
- lib/mongo/database/view.rb
- lib/mongo/index/view.rb
- lib/mongo/server_selector/selectable.rb
- The retryable module code will handle the socket exceptions so there
is no need for the overhead to ping before a read.
> Don't ping in server selection on reads:

- lib/mongo/address.rb
- lib/mongo/cluster.rb
- lib/mongo/server.rb
- lib/mongo/server/connection_pool.rb
- spec/mongo/server/connection_pool_spec.rb
- spec/mongo/server/connection_spec.rb
- spec/mongo/server_spec.rb
- Stops server monitor when Server is marked for GC.
- Scopes connection pools to cluster and fixes the Address equality as hash keys bug (was leaking pools)
> Stop monitor on server garbage collection.

- lib/mongo/grid/file.rb
- lib/mongo/grid/file/chunk.rb
- spec/mongo/grid/file/chunk_spec.rb
- spec/mongo/grid/file_spec.rb
Sometimes we have an IO that we don't want to read whole into memory, so we can transfer the chunking logic into IO terms and allow both strings and IOs.
> Give Grid::File ability to accept IO objects

- lib/mongo/grid/stream/read.rb
When streaming the chunked GridFS file, instead of assembling the chunk contents into a new string, we can just return the already allocated string. Normally I'm not pedantic about string allocations, but since these strings are parts of a file they're relatively large (default is 255 KB, but people can set it to more).
> Remove unnecessary string allocation

- lib/mongo/server/connection.rb
- spec/mongo/server/connection_spec.rb
This changes authenticator setup in the server connection to happen at
connect time, instead of connection instantiation. This fixes the
possibility of a running application with a connection open to a pre-3.0
server to get auth errors if the connection to the address was closed
and then reconnected against a server of 3.0 and higher and a different
auth mechanism.
The scenario to reproduce:
- Start an application against a MongoDB 2.6 server with MONGODB-CR
authentication with no auth_mech option specified on the client.
- Stop the running server, but leave the application running. The first
exception in the application will disconnect the connection.
- Upgrade the server to 3.0 and upgrade users to SCRAM-SHA-1. Restart
the server.
- The next application call would connect to the server, …
> Don't store authenticator on connection instance.

- lib/mongo/error/operation_failure.rb
Some more errors we've seen during failovers or crashes. I've added them to retry on my fork.
* `Mongo::Error::OperationFailure: unknown replica set d303f52f76534680956e00a707bbca89 (71)`
* `Mongo::Error::OperationFailure: dbclient error communicating with server: REDACTED (10278)`
> A couple more retries.

- lib/mongo/protocol/message.rb
- spec/mongo/protocol/reply_spec.rb
Thanks to @jonhyman for reporting this and pointing us to the solution
> RUBY-1078 Use default max message size when value is nil

- mongo.gemspec
With the import of mongo-ruby-driver v2.0 (1fc62d949269231e8e7639589a336276390dcc65), the mongo_console was removed. While the executable was later reintroduced (a30d72cfc17a23c95a08e1f275ae395120b3d3c7), the RubyGems wrapper was not installed into /usr/bin anymore, since it was never specified in .gemspec again.
This PR fixes the situation, since this seems to be non-intentional overlook.
> Install mongo_console again

- mongo.gemspec
'pry' is required and used by mongo_console executable[1], but is not installed by running `gem install mongo`, therefore leaving the executable unusable. 
[1] https://github.com/mongodb/mongo-ruby-driver/blob/15eb4b28462870bc8d54925e745c8da0b73543c7/bin/mongo_console#L4
> Add dependency on 'pry'

- lib/mongo/uri.rb
- spec/mongo/uri_spec.rb
With mongo shell, no problem:
```
└> mongo 'mongodb://admin:admin-secret@localhost:27020/api_development?authSource=admin'
MongoDB shell version: 3.2.6
connecting to: mongodb://admin:admin-secret@localhost:27020/api_development?authSource=admin
> 
```
ruby-mongo 2.2.5:
```
└> MONGO_URL='mongodb://admin:admin-secret@127.0.0.1:27020/api_development?authSource=admin' pry -r "mongo"
[1] pry(main)> client = Mongo::Client.new(ENV["MONGO_URL"])
D, [2016-06-13T16:20:51.510134 #20220] DEBUG -- : MONGODB | Adding 127.0.0.1:27020 to the cluster.
=> #<Mongo::Client:0x47061919412960 cluster=127.0.0.1:27020>
[2] pry(main)> client.database.collection("foo").count
D, [2016-06-13T16:20:56.331311 #20220] DEBUG -- : MONGODB | 127.0.0.1:27020 | api_development.count | STARTED | {"count"=>"foo", "query"=>{}} …
```
> When using connection URI, authSource should be used correctly

- lib/mongo/server/connection.rb
- spec/mongo/server/connection_spec.rb
as sayeth the spec: https://github.com/mongodb/specifications/blob/master/source/auth/auth.rst#authentication
> [v 2.2.6] RUBY-1122 Disconnect socket when auth fails

- lib/mongo/socket.rb
- spec/mongo/server/connection_spec.rb
Change the implementation of `Mongo::Socket.read_from_socket` method to check if the socket_timeout was exceeded while waiting for data.
This ensure that the client don't get stuck on a long query or a mongo server overload or a network problem.
> Fix socket timeout on read operations

- lib/mongo/server/connectable.rb
- lib/mongo/socket.rb
- spec/mongo/server/connection_spec.rb
- spec/support/authorization.rb
The time_left variable was only ever decremented if a WaitReadable error was raised.
This changes the logic so that timeout is taken into account regardless of whether bytes are successfully read or if there is a timeout when selecting.
Remove the default socket timeout, as it doesn't work in Ruby and was effectively infinite before.
> RUBY-1120 Don't set a default timeout on a socket and fix logic

- lib/mongo/server/description.rb
- lib/mongo/server/description/inspector.rb
- lib/mongo/server_selector/selectable.rb
- spec/mongo/client_spec.rb
- spec/mongo/max_staleness_spec.rb
- spec/mongo/server_selection_spec.rb
- spec/mongo/server_selector/nearest_spec.rb
- spec/mongo/server_selector/primary_preferred_spec.rb
- spec/mongo/server_selector/primary_spec.rb
- spec/mongo/server_selector/secondary_preferred_spec.rb
- spec/mongo/server_selector/secondary_spec.rb
Hi, it's me again with another bug in the ruby driver (I think) ☺
I tried using the `nearest` for my geo-redundant RS (2 servers with 1ms latency, 1 with 180ms) and noticed that it simply didn't work, it selects randomly any of my servers, including the 180ms one.
I dug a bit in the code and found out that there seems to be some mismatch in the units, some variables are supposed to contains ms but contains sec, so when the threshold (0.015s) was added to the slowest latency (ex: 0.001s) it is first multiplied by 1000, leading to a 15.001 sec threshold ^^
I fixed this by removing the multiplication and fixing all the specs stubbing ms whereas the real code works with seconds:
```ruby
production> Mongoid.default_client.cluster.servers.map &:average_round_trip_time
=> [0.00290229132, …
```
> Fix round trip time units mismatch

- lib/mongo/cluster.rb
- lib/mongo/cluster/cursor_reaper.rb
- lib/mongo/cursor.rb
Here are some fixes for ruby warnings that I see in my app.
> Ruby Warnings

- lib/mongo/socket.rb
- spec/mongo/server/connection_spec.rb
Ruby's Kernel#select can take a positive value or nil as the last argument (the socket timeout), but not a negative value.
> RUBY-1208 Verify that time remaining is positive or nil when checking if socket connect timed out

- lib/mongo/socket/tcp.rb
https://jira.mongodb.org/browse/RUBY-1211
I wanted to get some eyes on this to get some feedback - would consumers expect this to be enabled by default or should this be configured? If the answer is the later, should it be an explicit connection option that is passed through or via something like `ENV['MONGO_TCP_KEEPALIVE']`?
> RUBY-1211 Add Keep-Alive to Mongo::Socket::TCP.

- lib/mongo/connection/socket/tcp_socket.rb
Back patch of https://github.com/mongodb/mongo-ruby-driver/pull/857 to `1.x-stable`.
> RUBY-1211 Add Keep-Alive to Mongo::TCPSocket

- docs/index.txt
- docs/meta/404.txt
Docs changes now that we have a separate mongoid site https://docs.mongodb.com/mongoid/master/
> DOCS-9835 changes for separate mongoid docs site

- mongo.gemspec
`has_doc` is always set to `true` so there's no point in setting it (https://github.com/rubygems/rubygems/blob/d8d235f1eeb6da0fb289ce0415ad049153f9adc9/lib/rubygems/specification.rb#L1411).
> gemspec: Remove relic has_doc attribute

- lib/mongo/server/description.rb
- spec/mongo/server/description_spec.rb
This pull request solves the problem discussed at the following URL.
https://groups.google.com/forum/#!msg/mongodb-user/moEu4STgzUg/HMnZhj2mDQAJ
Since lastWrite changes like localTime, I think it is correct to ignore them when comparing config.
> RUBY-1223 Ignore lastWrite when comparing server descriptions

- lib/mongo/client.rb
- lib/mongo/collection.rb
- lib/mongo/collection/view.rb
- lib/mongo/collection/view/aggregation.rb
- lib/mongo/collection/view/builder/op_query.rb
- lib/mongo/collection/view/iterable.rb
- lib/mongo/collection/view/map_reduce.rb
- lib/mongo/collection/view/readable.rb
- lib/mongo/database.rb
- lib/mongo/grid/fs_bucket.rb
- lib/mongo/grid/stream/read.rb
- lib/mongo/operation/read_preference.rb
- lib/mongo/operation/specifiable.rb
- spec/mongo/client_spec.rb
- spec/mongo/collection/view/readable_spec.rb
- spec/mongo/collection_spec.rb
- spec/mongo/cursor_spec.rb
- spec/mongo/database_spec.rb
- spec/mongo/grid/fs_bucket_spec.rb
- spec/mongo/grid/stream/read_spec.rb
- spec/mongo/operation/specifiable_spec.rb
- spec/mongo/uri_spec.rb
The driver made no distinction between a read preference set in options and a server selector. A server selector must use the user-defined read preference or default to a primary. The read preference is either set in options or is nil.
These changes are necessary when implementing OP_MSG so that we aren't sending a read preference to the server if the user hasn't defined one. In the case that the user hasn't defined one on the client or collection, we must not send the read preference so that the default server-side can be used.
> Separate concept of user-defined read preference and server selection

- lib/mongo/operation/commands/aggregate.rb
- lib/mongo/operation/commands/collections_info.rb
- lib/mongo/operation/commands/command.rb
- lib/mongo/operation/commands/create.rb
- lib/mongo/operation/commands/drop.rb
- lib/mongo/operation/commands/drop_database.rb
- lib/mongo/operation/commands/indexes.rb
- lib/mongo/operation/commands/list_collections.rb
- lib/mongo/operation/commands/list_indexes.rb
- lib/mongo/operation/commands/user_query.rb
- lib/mongo/operation/commands/users_info.rb
Amended documentation in the `operation/commands` folder to add clarity and consistency to command documentation.
- operation/commands/aggregate.rb
- operation/commands/collections_info.rb
- operation/commands/command.rb
- operation/commands/create.rb
- operation/commands/drop_database.rb
- operation/commands/drop.rb
- operation/commands/indexes.rb
- operation/commands/list_collections.rb
- operation/commands/list_indexes.rb
- operation/commands/user_query.rb
- operation/commands/users_info.rb
> amended documentation to add clarity

- spec/mongo/change_stream_examples_spec.rb
These tests were previously failing frequently on Evergreen because the operations launched in the thread didn't seem to always execute. I've changed the test to create two threads and force the main thread to wait until each completes in succession.
> Update change stream examples test

- lib/mongo/uri.rb
- spec/mongo/uri_spec.rb
mongoid 7.0.0.beta
mongo 2.5.0.beta
mongoid.yml
```yml
development:
clients:
default:
uri: mongodb:///tmp/mongodb-27017.sock/database_name
```
When set MongoDB URI string `mongodb:///tmp/mongodb-27017.sock/database_name`, it's fails with error when call `rails s`
``` 
Mongo::Error::InvalidURI (Bad URI: mongodb:///tmp/mongodb-27017.sock/database_name
UNIX domain sockets must be urlencoded.
MongoDB URI must be in the following format: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
Please see the following URL for more information: http://docs.mongodb.org/manual/reference/connection-string/
):
```
Following the documentation https://docs.mongodb.com/manual/reference/connection-string/#unix-domain-socket we should pass string …
> Fix unix domain socket connection for mongoid

- .evergreen/.evg.yml
Currently, the s3 uploads of the server logs fail on evergreen due to a quirk in how the s3.put command deals with absolute paths (see the line starting with "[2018/04/12 11:45:39.716] Command failed: missing file" in [this log](https://evergreen.mongodb.com/task_log_raw/mongo_ruby_driver_rhel70_all_mongodbs_all_rubies_all_topologies_all_auth_all_ssl__mongodb_version~2.6_topology~replicaset_auth~auth_ssl~nossl_ruby~ruby_1.9_test_fe269bf89f832912e0f2779ba7e47783d785ee24_18_04_12_14_38_42/0?type=T&text=true). To fix this, we can just use save the tarball in the current working directory and upload it from there instead of relying on a proper expansion of $PROJECT_DIRECTORY.
See [here](https://evergreen.mongodb.com/build/mongo_ruby_driver_rhel70_all_mongodbs_all_rubies_all_topologies_all_auth …
> fix s3 uploads

- spec/mongo/client_spec.rb
- Repair descriptions of inequality tests to match their behavior
- Test different clusters in addition to different options
> Repair description & extend client spec for equality

- docs/tutorials/ruby-driver-admin-tasks.txt
- lib/mongo/auth/cr.rb
- lib/mongo/auth/cr/conversation.rb
- lib/mongo/uri.rb
I could not find any warnings in the code for deprecated functionality, hence just added `@deprecated` tags.
https://jira.mongodb.org/browse/RUBY-1288
>  Deprecate MONGODB-CR authentication mechanism

- lib/mongo/address.rb
- lib/mongo/address/ipv6.rb
- spec/mongo/address/ipv6_spec.rb
- spec/mongo/address_spec.rb
- spec/mongo/client_spec.rb
The main change in this PR is in the to_s method to correctly serialize IPv6 addresses with ports as `[::1]:27017` instead of `::1:20017`.
The parser was changed to accept `::1` as a valid address, validate the host part of the address using stdlib's `ipaddr` library, and produce more helpful exceptions when given invalid input. These changes are primarily to improve developer experience.
https://jira.mongodb.org/browse/RUBY-1298
> Ipv6 address stringification fix

- lib/mongo/error/bulk_write_error.rb
Example referenced BulkWriteFailure whereas the class name is BulkWriteError.
> Correctly use BulkWriteError in example

- spec/spec_helper.rb
Instead run all tests and show all errors.
> Disable fail fast when not in CI

- mongo.gemspec
The dup call makes `bundle install` work on ruby 1.9.3. Without it rubygems tries to modify version which fails because Mongo::VERSION is frozen.
I am not sure how e.g. Travis is succeeding on 1.9.3 without this patch - perhaps it does not use vanilla 1.9.3.
> Make bundle install work in ruby 1.9.3

- .rspec
- .travis.yml
- Gemfile
- spec/spec_helper.rb
This PR reduces Travis log size from ~10,000 lines to ~1,000 lines.
A big change here is replacement of default documentation formatter with Fuubar which provides 1) immediate failure messages for failing tests, 2) progress bar for overall test runtime and 3) compact overall output.
> Reduce travis log size

- lib/mongo/monitoring/command_log_subscriber.rb
This shortens the log entries a bit.
> Millisecond precision for duration should be sufficient

- spec/lite_spec_helper.rb
- spec/spec_helper.rb
- spec/spec_tests/command_monitoring_spec.rb
- spec/spec_tests/connection_string_spec.rb
- spec/spec_tests/crud_spec.rb
- spec/spec_tests/dns_seedlist_discovery_spec.rb
- spec/spec_tests/sdam_monitoring_spec.rb
- spec/spec_tests/sdam_spec.rb
- Created a lite spec helper to be used instead of the full spec helper for tests that do not interact with a real mongod. This is meant to accomplish two goals: 1) remove noise from global client init for tests that also deal with client initialization, like topology ones and 2) speed up the tests.
- Changed two more tests to have explicit skips when preconditions are not met.
> Lite specs

- lib/mongo/event.rb
- lib/mongo/event/base.rb
- lib/mongo/event/description_changed.rb
- lib/mongo/event/member_discovered.rb
- lib/mongo/event/primary_elected.rb
- lib/mongo/event/standalone_discovered.rb
- lib/mongo/monitoring.rb
- lib/mongo/monitoring/event.rb
- lib/mongo/monitoring/event/command_failed.rb
- lib/mongo/monitoring/event/command_started.rb
- lib/mongo/monitoring/event/command_succeeded.rb
- lib/mongo/monitoring/event/server_closed.rb
- lib/mongo/monitoring/event/server_description_changed.rb
- lib/mongo/monitoring/event/server_opening.rb
- lib/mongo/monitoring/event/topology_changed.rb
- lib/mongo/monitoring/event/topology_closed.rb
- lib/mongo/monitoring/event/topology_opening.rb
- lib/mongo/monitoring/publishable.rb
- spec/spec_tests/sdam_monitoring_spec.rb
This is to assist in understanding SDAM state transitions, ultimately for https://jira.mongodb.org/browse/RUBY-1332
Eventually the various debug events should be organized, and support being turned on and off, by a subsystem as otherwise they would be too noisy.
> Add debug logging for topology events

- Gemfile
- lib/mongo/server/description/features.rb
- lib/mongo/server_selector/selectable.rb
- spec/spec_tests/sdam_spec.rb
- spec/support/sdam/rs/normalize_case_me.yml
- spec/support/sdam/sharded/compatible.yml
- spec/support/sdam/sharded/mongos_disconnect.yml
- spec/support/sdam/sharded/non_mongos_removed.yml
- spec/support/sdam/sharded/too_new.yml
- spec/support/sdam/sharded/too_old.yml
- spec/support/sdam/single/compatible.yml
- spec/support/sdam/single/direct_connection_external_ip.yml
- spec/support/sdam/single/direct_connection_mongos.yml
- spec/support/sdam/single/direct_connection_rsarbiter.yml
- spec/support/sdam/single/direct_connection_rsprimary.yml
- spec/support/sdam/single/direct_connection_rssecondary.yml
- spec/support/sdam/single/direct_connection_standalone.yml
- spec/support/sdam/single/not_ok_response.yml
- spec/support/sdam/single/standalone_removed.yml
- spec/support/sdam/single/too_new.yml
- spec/support/sdam/single/too_old.yml
This is part of https://jira.mongodb.org/browse/RUBY-1332 which deals with sdam subdirectory. The only code change needed was raising an error when any server in a cluster has an unacceptable wire protocol, whereas before only the server that was selected was subject to wire protocol check.
Verbose cluster/server inspectors were added for debugging.
> RUBY-1332 Sync SDAM spec tests (not monitoring)

- spec/spec_tests/sdam_spec.rb
Minor change for https://jira.mongodb.org/browse/RUBY-1332
> Pass uri directly to client constructor in sdam tests

- lib/mongo/monitoring.rb
- lib/mongo/monitoring/event/command_failed.rb
- lib/mongo/monitoring/event/command_started.rb
- lib/mongo/monitoring/event/command_succeeded.rb
- lib/mongo/monitoring/publishable.rb
- spec/integration/command_monitoring_spec.rb
- spec/mongo/client_spec.rb
- spec/mongo/collection_spec.rb
- spec/mongo/database_spec.rb
- spec/mongo/monitoring/event/command_failed_spec.rb
- spec/mongo/monitoring/event/command_started_spec.rb
- spec/mongo/monitoring/event/command_succeeded_spec.rb
- spec/mongo/monitoring_spec.rb
- spec/mongo/session/session_pool_spec.rb
Added an integration test to verify command monitoring functionality per the spec. Spec needed to be fixed - https://github.com/mongodb/specifications/pull/359.
Changes made to monitoring code itself:
- DRY the code - extract Subscribable module with common methods for per-client and global subscribers
- Add unsubscribe method so that the testing can be done
- Document how multiple subscriptions of the same listener are handled
- ~~Expose command arguments in started and failure events since the events have them~~
- Expose failure document in failure events per specification
- `command_name` on command monitoring events is now always a string, as was documented
> Command monitoring improvements and tests

- lib/mongo/collection/view/readable.rb
- spec/mongo/collection_spec.rb
- spec/support/constraints.rb
- spec/support/shared/session.rb
A user is able to explicitly provide a session still,
but the driver will execute the parallel scan outside of a session
by default.
https://jira.mongodb.org/browse/RUBY-1347
> RUBY-1347 Do not use sessions by default in parallel scan.

- spec/mongo/socket_spec.rb
- spec/spec_helper.rb
I fixed some tests on JRuby.
* Fix NameRrror for TimeoutInterrupt on JRuby.
See current master branch's CI https://travis-ci.org/mongodb/mongo-ruby-driver/jobs/403328850
```
uninitialized constant Constraints::TimeoutInterrupt
```
* not existing Errno::ENOMEDIUM object.
I reported a issue to JRuby project.
https://github.com/jruby/jruby/issues/5257
Here is the result on my repository.
https://travis-ci.org/junaruga/mongo-ruby-driver/builds/406455599
Still one test case is failure.
Feel free to ask me or pick up a part of the source code.
> Fix test error on JRuby.

- spec/integration/transactions_examples_spec.rb
The loops are unnecessary in ruby.
> Use retry syntax in Ruby transaction examples

- .travis.yml
Given the long running times of our Travis jobs, it has been requested that we only test the latest version of MongoDB on Travis rather than every version (since we already test all versions on Evergreen). I also don't think it's necessary to test multiple different stable versions of Ruby for similar reasons.
> stop building every mongodb version on travis

- spec/support/lite_constraints.rb
Testing mongo 2.6.2 with
~~~
$ rpm -q mongodb-server
mongodb-server-4.0.1-1.fc29.x86_64
$ rpm -q ruby
ruby-2.5.1-100.fc30.x86_64
~~~
I see the following test results:
~~~
11) Change stream integration watch+next no errors next returns changes
~~~
This appears to be wrong and this PR fixes the issue.
> Fix the only_mri constraint.

- lib/mongo/auth.rb
All mechanisms take a single argument which is the user, hence the
special case for SCRAM does not work. But, it appears that that
code is never run anyways.
> Remove dead code

- spec/lite_spec_helper.rb
The Travis job testing against server version 2.6 has been failing recently due to the failed import of `pry` not properly being caught. Simply adding `Exception` as the type of error to catch rather than leaving it blank fixes this.
> minor: fix catching of all errors for pry import

- lib/mongo/session/session_pool.rb
I assume that what happened here was that `@cluster.logical_session_timeout` changed in the middle of the execution, since it comes from an isMaster command. I believe we had a server failure at or around this time.
> Memoize a variable that could change by a separate thread.

- .evergreen/.evg.yml
Since these are very fast there is no harm in testing the min ruby versions.
> Run enterprise auth tests on old rubies

- docs/tutorials/ruby-driver-create-client.txt
- lib/mongo/client.rb
- lib/mongo/uri.rb
- spec/spec_tests/data/uri_options/auth-options.yml
- spec/spec_tests/data/uri_options/compression-options.yml
- spec/spec_tests/data/uri_options/connection-options.yml
- spec/spec_tests/data/uri_options/read-preference-options.yml
- spec/spec_tests/data/uri_options/tls-options.yml
- spec/support/connection_string.rb
The URI options have been merged, so this PR includes the changes that have been made since the initial commit for them.
Additionally, it appears that the test runner wasn't properly comparing the expected URI options to their parsed options of different names, so I've fixed that as well.
> RUBY-1559 Update URI option spec tests and fix comparisons

- docs/tutorials/ruby-driver-create-client.txt
- lib/mongo/client.rb
The diff is a little weird since I reordered everything to be in alphabetical order. It might be easier to just look at the final state of the files rather than the diff.
> RUBY-1676 Add missing client option documentation

- .travis.yml
The Travis build was failing on Ruby 1.9.3 due to trying to update bundler to a newer version than supports 1.9.3. Given that the commands doing to update appear to be copied from the [Travis documentation](https://docs.travis-ci.com/user/languages/ruby/#bundler-20) describing how to update to bundler 2.0 (which does not support 1.9.3), I disabled them from running in the job that uses 1.9.3.
> minor: fix travis with ruby 1.9

- lib/mongo/uri/srv_protocol.rb
- spec/mongo/uri/srv_protocol_spec.rb
https://jira.mongodb.com/browse/RUBY-1749
> Fix RUBY-1749 Two-part hostnames are accepted by the driver for SRV queries with a trailing dot

- lib/mongo/database/view.rb
As far as I can tell the -1 limit is ignored by the driver, just like
a nil limit would be ignored. However the call on server is problematic
with the new retryable reads API since server may change during a
read operation.
> RUBY-1562 Remove -1 limit in db view

- spec/spec_tests/crud_spec.rb
- spec/spec_tests/data/retryable_writes/bulkWrite-serverErrors.yml
- spec/spec_tests/data/retryable_writes/deleteOne-serverErrors.yml
- spec/spec_tests/data/retryable_writes/findOneAndDelete-serverErrors.yml
- spec/spec_tests/data/retryable_writes/findOneAndReplace-serverErrors.yml
- spec/spec_tests/data/retryable_writes/findOneAndUpdate-serverErrors.yml
- spec/spec_tests/data/retryable_writes/insertMany-serverErrors.yml
- spec/spec_tests/data/retryable_writes/insertOne-serverErrors.yml
- spec/spec_tests/data/retryable_writes/replaceOne-serverErrors.yml
- spec/spec_tests/data/retryable_writes/updateOne-serverErrors.yml
- spec/spec_tests/retryable_writes_spec.rb
- spec/support/crud.rb
- spec/support/crud/read.rb
- spec/support/crud/requirement.rb
- spec/support/crud/spec.rb
- spec/support/crud/test.rb
- spec/support/crud/write.rb
This PR contains changes to the crud spec runner needed to support retryable reads, specifically:
- Adding additional read operations not previously implemented by the runner
- Supporting additional operation targets (database & client in addition to collection, for change stream tests)
- Supporting runOn server version/topology requirements
> RUBY-1562 spec preparation

- spec/support/spec_config.rb
Right now the CI tests are not started correctly because of below issue.
https://travis-ci.org/mongodb/mongo-ruby-driver/builds/536965194
```
NoMethodError: undefined method `[]' for nil:NilClass
/home/travis/build/mongodb/mongo-ruby-driver/spec/support/spec_config.rb:123:in `uri_option_or_env_var'
```
After this PR, you still see below test failures.
But it's better than current situation.
Here is my repository's result.
https://travis-ci.org/junaruga/mongo-ruby-driver/builds/538259907
https://api.travis-ci.org/v3/job/538259909/log.txt
```
11282 examples, 3 failures, 5300 pending
Failed examples:
rspec ./spec/mongo/server/connection_spec.rb[1:1:1:6:1:1] # Mongo::Server::Connection#connect! when no socket exists when #authenticate! raises an exception behaves like failing connection …
```
> Fix NoMethodError: undefined method `[]' for nil:NilClass for tests.

- docs/reference/driver-compatibility.txt
This uses the new no-padding class added to docs-tools
in https://github.com/mongodb/docs-tools/pull/300 .
The padding on the compatibility tables is interfering with
the ability of the table to stretch to fit.
https://jira.mongodb.org/browse/DOCS-12771
https://docs-mongodbcom-staging.corp.mongodb.com/ruby-driver/bush/master/reference/driver-compatibility.html
> DOCS-12711 Fit compatibility tables in view by removing padding

- spec/spec_tests/data/change_streams/change-streams.yml
- spec/support/change_streams/operation.rb
Includes RUBY-1416 Update ChangeStream tests for 4.1.1 "drop" notifications
> RUBY-1636 Resync change stream tests to test all new notification types

- .evergreen/config.yml
- lib/mongo/collection/view/builder/aggregation.rb
- lib/mongo/collection/view/builder/find_command.rb
- lib/mongo/collection/view/builder/map_reduce.rb
- lib/mongo/collection/view/readable.rb
- lib/mongo/lint.rb
- lib/mongo/operation/parallel_scan/command.rb
- lib/mongo/operation/parallel_scan/op_msg.rb
- lib/mongo/operation/shared/sessions_supported.rb
- lib/mongo/session.rb
- lib/mongo/uri.rb
- spec/integration/read_concern_spec.rb
- spec/mongo/collection_spec.rb
- spec/mongo/uri_option_parsing_spec.rb
- spec/support/connection_string.rb
- spec/support/transactions/operation.rb
- spec/support/transactions/test.rb
https://jira.mongodb.com/browse/RUBY-1875
> RUBY-1875 Pass read concern options through normal driver mechanisms

- lib/mongo/client.rb
- spec/mongo/client_construction_spec.rb
https://jira.mongodb.com/browse/RUBY-1876
> Fix RUBY-1876 Can't disable retryable read/writes via URI options

- lib/mongo/server/connection.rb
- lib/mongo/server/connection_pool.rb
- spec/mongo/server/connection_pool_spec.rb
- spec/mongo/server/connection_spec.rb
First part of 1871 followup work: Distinguish between connection being checked into the correct pool, but out of sequence vs connection being checked into a foreign pool
> RUBY-1871 Associate connections with pools

- lib/mongo/auth.rb
- lib/mongo/error.rb
- lib/mongo/error/auth_error.rb
- lib/mongo/server/connection_pool.rb
- lib/mongo/server/connection_pool/connection_pool_populator.rb
This does not include an entire audit of the driver; that will be in a future PR.
> RUBY-1887 add AuthError and rescue it with Mongo::Error (wip)

- lib/mongo/cluster.rb
- lib/mongo/cluster/sdam_flow.rb
- lib/mongo/operation/shared/executable.rb
- lib/mongo/server.rb
- lib/mongo/server/connection.rb
- spec/integration/sdam_error_handling_spec.rb
- spec/mongo/server/connection_spec.rb
https://jira.mongodb.com/browse/RUBY-1894
> RUBY-1894 Clear connection pools when monitor ismaster times out

- lib/mongo/server.rb
- spec/integration/sdam_error_handling_spec.rb
- spec/integration/step_down_spec.rb
- spec/mongo/server/connection_spec.rb
- spec/mongo/server/monitor/connection_spec.rb
This version always clears connection pools whenever a server becomes unknown.
This results in repeated pool clears sometimes which is suboptimal but not really wrong.
Driver version 2.11+ has the correct implementation of pool clearing which makes use
of refactoring done for background connection pool thread/SRV polling.
> Backport RUBY-1894 Clear connection pools when monitor ismaster times out (#1475) (#1477)

- lib/mongo/socket.rb
- lib/mongo/socket/ssl.rb
- lib/mongo/socket/tcp.rb
- lib/mongo/socket/unix.rb
- spec/mongo/server/connection_spec.rb
- spec/mongo/socket_spec.rb
- spec/support/cluster_config.rb
- spec/support/spec_config.rb
https://jira.mongodb.com/browse/RUBY-1898
> Fix RUBY-1898 Socket reads may raise Timeout::Error

- docs/quick-start.txt
- docs/tutorials/ruby-driver-crud-operations.txt
This addresses an issue raised in https://jira.mongodb.org/browse/DOCS-9486, no nested document query example.
I had to adjust the example slightly in the quick-start. Can modify more as needed, I just want to get the ball rolling.
> adds example for nested doc query

- lib/mongo/client.rb
- lib/mongo/uri.rb
- spec/mongo/uri/srv_protocol_spec.rb
- spec/mongo/uri_option_parsing_spec.rb
- spec/mongo/uri_spec.rb
- spec/support/auth.rb
- spec/support/connection_string.rb
Part one of [RUBY-1913](https://jira.mongodb.org/browse/RUBY-1913)
Any references to the `$external` auth source was being changed into a symbol, which is not a type that the server recognizes. This removes all references to `:external` and deletes related code.
> RUBY-1913 Do not convert auth source from $external to :external because server does not recognize symbol database names

- lib/mongo/background_thread.rb
- spec/mongo/server/monitor_spec.rb
Threads that are stopped via a disconnect can't actually be restarted:
```ruby
> server.instance_variable_get(:@monitor).instance_variable_get(:@thread).alive?
=> true
> server.disconnect!
=> true
> server.reconnect!
=> true
> server.instance_variable_get(:@monitor).instance_variable_get(:@thread).alive?
=> false
> server.instance_variable_get(:@monitor).instance_variable_get(:@thread).alive?
=> false
> server.instance_variable_get(:@monitor).instance_variable_get(:@thread).alive?
=> false
```
I can't run tests for some reason, likely due to my config perhaps I don't have some kind of environment variables set up. But I believe this test should pass based on the example code above.
```ruby
NoMethodError:
undefined method `map' for true:TrueClass
Did you mean?  tap
```
> Fix RUBY-1944 Background threads such as the Monitor cannot restart once stopped

- .evergreen/run-tests-with-kerberos.sh
- spec/integration/client_options_spec.rb
- spec/mongo/uri_spec.rb
This is part two of my work for [RUBY-1913](https://jira.mongodb.org/browse/RUBY-1913).
In [RUBY-1258](https://github.com/mongodb/mongo-ruby-driver/commit/c31f62c0d217727ca466db862469ceaddf76b583#diff-e7786d37b967fce59a4cd10176f3a85aR441), I updated Mongo::URI to set some default options that it passes to the client. This works if a user is connecting to a MongoDB instance using exclusively URI options, but it doesn't help if the user wants to pass those options directly into the client and get the same defaults.
For example:
```
> client = Mongo::Client.new('mongodb://localhost:27018/?authMechanism=MONGODB-X509&tls=true&tlsCAFile=/path/to/ca&tlsCertificateKeyFile=/path/to/cert')
> client.options
=> {"database"=>"admin", "auth_source"=>"$external", "auth_mech"=>:mongodb_x509, "ssl"=>true, …
```
> RUBY-1913 Client auth option integration tests

- docs/index.txt
- docs/tutorials/ruby-driver-authentication.txt
- docs/tutorials/ruby-driver-user-management.txt
- docs/tutorials/user-management.txt
- lib/mongo/auth/user/view.rb
- Remove user documentation from the Authentication tutorial
- Create a separate User Management tutorial with information about creating, viewing, updating, and removing users
> Improve User Management Documentation

- lib/mongo/crypt/binary.rb
- spec/mongo/crypt/binary_spec.rb
It isn't great API design to force users of the libmongocrypt binding to do their own memory management, so I'm introducing an API that creates a new `Mongo::Crypt::Binary` object in the context of a block and then closes it upon completion of that block (or upon rescuing an error).
> RUBY-1965 Introduce a block API for the Mongo::Crypt::Binary object

- lib/mongo/crypt.rb
- lib/mongo/crypt/binary.rb
- lib/mongo/crypt/binding.rb
- lib/mongo/crypt/handle.rb
- lib/mongo/crypt/status.rb
- lib/mongo/error/crypt_error.rb
- spec/mongo/crypt/binary_spec.rb
- spec/mongo/crypt/binding/mongocrypt_spec.rb
- spec/mongo/crypt/handle_spec.rb
- spec/mongo/error/crypt_error_spec.rb
This is the last PR for RUBY-1965 -- after this I should be able to initialize a ClientEncryption object and start using some of these objects.
In this PR:
- Change `Mongo::Crypt::Binary` to take a string as input rather than an array of bytes.
- Add binding for mongocrypt_t methods
- Add an API around mongocrypt_t called `Mongo::Crypt::Handle` (this is what it's called in the spec)
- Change the API of `Mongo::Error::CryptError` to be an error specifically returned from libmongocrypt
> RUBY-1965 Create Mongocrypt handle binding

- lib/mongo/crypt/binary.rb
I accidentally used an FFI API method that has no corresponding Java implementation.
> Fix broken JRuby test for FLE

- lib/mongo/client_encryption.rb
- lib/mongo/crypt/binary.rb
- lib/mongo/crypt/context/context.rb
- lib/mongo/crypt/context/data_key_context.rb
- lib/mongo/crypt/context/explicit_decryption_context.rb
- lib/mongo/crypt/context/explicit_encryption_context.rb
- lib/mongo/crypt/handle.rb
- lib/mongo/crypt/status.rb
- spec/integration/explicit_encryption_spec.rb
- spec/mongo/client_encryption_spec.rb
- spec/mongo/crypt/binary_spec.rb
- spec/mongo/crypt/data_key_context_spec.rb
- spec/mongo/crypt/handle_spec.rb
- spec/mongo/crypt/status_spec.rb
`FFI::AutoPointer` takes a custom release method and automatically releases memory allocated by libmongocrypt when the associated Ruby object goes out of scope.
- This means there is no need for `close` methods on Ruby objects
- There is also no need for these objects to have block APIs
> RUBY-2022 Use FFI::AutoPointer to automatically de-allocate memory for libmongocrypt

- lib/mongo/database.rb
Note I chose to link to `[ Mongo::Operation::Result ]` instead of simply `[ Result ]` to ensure links were generated appropriately.
Note for consistency we could change this to `[ Result ]`, but then we'd lose the link
> RUBY-2017 Modify result type of Mongo::Database#command within the inline docs

- lib/mongo/cluster.rb
- spec/mongo/cluster_spec.rb
We made a configuration change for our connection strings and mistakenly duplicated a mongoS host, which then broke processes when they tried to start up. The issue is that Cluster#add will return nil if the address already exists, and you'll receive this error (taken from the test without the patch).
```
NoMethodError: undefined method `start_monitoring' for nil:NilClass
0) Mongo::Cluster initialize when there are duplicate addresses does not error out
Failure/Error:[0mserver.start_monitoring
NoMethodError:
undefined method `start_monitoring' for nil:NilClass
```
> Fix RUBY-2030 Client/Cluster construction fails when duplicate seed addresses are provided

- lib/mongo/client_encryption.rb
- lib/mongo/crypt/binding.rb
- lib/mongo/crypt/context/context.rb
- lib/mongo/crypt/handle.rb
- spec/mongo/crypt/data_key_context_spec.rb
- spec/mongo/crypt/explicit_decryption_context_spec.rb
- spec/mongo/crypt/explicit_encryption_context_spec.rb
Also change the context api (data key context, explicit encryption context, explicit decryption context) to be more consistent with the rest of the `Crypt` API that's been built so far.
> RUBY-2014 Send logging messages from libmongocrypt to Mongo::Logger

- lib/mongo/auth/user.rb
- lib/mongo/crypt/binding.rb
- lib/mongo/crypt/encrypter.rb
- lib/mongo/crypt/handle.rb
- spec/mongo/client_construction_spec.rb
- spec/mongo/crypt/auto_encryption_context_spec.rb
- spec/mongo/crypt/data_key_context_spec.rb
- spec/mongo/crypt/explicit_decryption_context_spec.rb
- spec/mongo/crypt/explicit_encryption_context_spec.rb
- spec/mongo/crypt/handle_spec.rb
Add the ability for a libmongocrypt Handle to accept a schema map, which specifies the fields to be encrypted/decrypted during auto encryption.
> RUBY-1924: Schema Map

- lib/mongo/client.rb
- lib/mongo/crypt/auto_encrypter.rb
- lib/mongo/crypt/encrypter.rb
- spec/integration/client_construction_spec.rb
- spec/mongo/client_construction_spec.rb
- spec/mongo/client_updating_spec.rb
I realized that the way I was creating the key vault client meant that it was trying to auto encrypt, which it should not do. I also updated the encrypter to keep track of a key vault client that it spawns and close it on teardown.
> RUBY-2028 Allow user to update auto_encryption_options using Client#update_options

- .evergreen/config.yml
- .evergreen/run-fle-tests.sh
- lib/mongo/client_encryption.rb
- lib/mongo/crypt.rb
- lib/mongo/crypt/auto_decryption_context.rb
- lib/mongo/crypt/auto_encryption_context.rb
- lib/mongo/crypt/binary.rb
- lib/mongo/crypt/binding.rb
- lib/mongo/crypt/context.rb
- lib/mongo/crypt/data_key_context.rb
- lib/mongo/crypt/explicit_decryption_context.rb
- lib/mongo/crypt/explicit_encryption_context.rb
- lib/mongo/crypt/handle.rb
- lib/mongo/crypt/hooks.rb
- lib/mongo/crypt/status.rb
- spec/mongo/client_encryption_spec.rb
- spec/mongo/crypt/auto_decryption_context_spec.rb
- spec/mongo/crypt/auto_encryption_context_spec.rb
- spec/mongo/crypt/binary_spec.rb
- spec/mongo/crypt/binding/context_spec.rb
- spec/mongo/crypt/binding/mongocrypt_spec.rb
- spec/mongo/crypt/data/key_document.json
- spec/mongo/crypt/explicit_decryption_context_spec.rb
- spec/mongo/crypt/explicit_encryption_context_spec.rb
- spec/mongo/crypt/helpers/crypto_hooks_helper.rb
- spec/mongo/crypt/helpers/mongo_crypt_spec_helper.rb
- spec/mongo/crypt/status_spec.rb
- spec/support/utils.rb
Crypto functionality now works with a nocrypto build of libmongocrypt!
I have also made some API changes:
- Make the entire crypto API private except for the things designated as public by the client-side encryption spec
- Change the `Binary` and `Status` APIs to allow those objects to be initialized using an existing pointer to an underlying C object (for use in crypto hooks)
- Change the `Handle` API to be more consistent (make every argument that is optional part of `options` rather than its own argument)
> RUBY-1939 Bind Ruby crypto hooks to libmongocrypt

- spec/mongo/crypt/auto_decryption_context_spec.rb
- spec/mongo/crypt/auto_encryption_context_spec.rb
- spec/mongo/crypt/explicit_decryption_context_spec.rb
- spec/mongo/crypt/explicit_encryption_context_spec.rb
There is some copy + paste in these specs, which I will clean up in a follow-up PR.
> RUBY-2007 Make sure all contexts initialize properly when Mongocrypt uses AWS KMS options

- lib/mongo/client.rb
- lib/mongo/crypt/auto_encrypter.rb
- spec/integration/fle_reconnect_spec.rb
- spec/mongo/client_updating_spec.rb
[https://jira.mongodb.org/browse/RUBY-2105](https://jira.mongodb.org/browse/RUBY-2105)
Test that the master client, mongocryptd_client, and key_vault_client all function when `reconnect` is called on the master client.
I also refactored the logic for updating client_encryption_options. It now tears down all the encryption logic and builds it back up again whenever encryption options change.
> RUBY-2105 In auto-encryption, when top-level client disconnects/reconnects, make sure that the slaved clients also reconnect

- lib/mongo/operation/result.rb
- spec/mongo/collection/view/change_stream_spec.rb
- spec/mongo/error/operation_failure_spec.rb
The driver currently supports either zero or one replies per operation.
Remove references to multiple replies.
This commit also revises docstrings in Operation::Result to match
current code behavior.
> RUBY-1924 Remove references to multiple replies in Operation::Result

- spec/README.md
The file `/spec/support/certificates/ca.pem` does not exist, so these instructions won't work if somebody runs them. They do work when you write `ca.crt` instead, which is the actual name of the file.
> Specify correct certificate name in SSL test instructions

- lib/mongo/client_encryption.rb
- lib/mongo/crypt/auto_encrypter.rb
- lib/mongo/crypt/binding.rb
- lib/mongo/crypt/data_key_context.rb
- lib/mongo/crypt/encrypter.rb
- lib/mongo/crypt/explicit_encryption_context.rb
- lib/mongo/crypt/handle.rb
- spec/mongo/client_encryption_spec.rb
- spec/mongo/crypt/data_key_context_spec.rb
This is the first PR of a few, with the purpose of making it possible to refer to encryption keys by alternate names.
> RUBY-2008 Allow user to specify key alt names when creating a data key

- docs/index.txt
- docs/tutorials/client-side-encryption.txt
This PR creates a client-side encryption tutorial. The sections filled in so far are installation instructions and automatic encryption. I have run the auto-encryption code on my machine and confirmed that it behaves as expected.
Once everything looks good here, I will create a follow-up PR for explicit encryption, and another one for the three sections at the bottom. I want to explain how to create a master key, a data key, and a schema map using local KMS options as well as AWS KMS options.
> RUBY-1974 Add a tutorial for Automatic Encryption

- lib/mongo/crypt/encryption_io.rb
- lib/mongo/database.rb
- lib/mongo/database/view.rb
- spec/mongo/database_spec.rb
Integrating with libmongocrypt requires listCollections to be performed with a filter, which Ruby hasn't supported. I've been hacking around it, but that makes the FLE command monitoring specs fail, so I figured I would fix this if it was easy and didn't break the user-facing API. Let me know if you think this is okay and I'll make a JIRA ticket for it as well.
> RUBY-2142 Add a filter option to list_collections

- lib/mongo/client.rb
- lib/mongo/crypt/encryption_io.rb
- spec/integration/auto_encryption_command_monitoring_spec.rb
- spec/support/spec_config.rb
Based on the way that the auto encrypter was previously being set up, the key vault client was not actually getting auto encryption options. I have fixed that, added tests that would fail without this change, and updated documentation about the number of connections required by auto encryption.
> RUBY-1926 Ensure that key vault client has auto encryption options

- docs/tutorials/client-side-encryption.txt
- lib/mongo/crypt/binding.rb
- lib/mongo/crypt/handle.rb
- spec/mongo/crypt/handle_spec.rb
- spec/support/crypt.rb
Though I think it makes more sense to to convert the master key to base64 before storing it, it isn't consistent with the spec, so just store it as a string of bytes.
> RUBY-1926 Don't Base64 encode local master keys

- docs/tutorials/client-side-encryption.txt
- lib/mongo/client_encryption.rb
- lib/mongo/crypt/explicit_encrypter.rb
- lib/mongo/crypt/explicit_encryption_context.rb
- spec/integration/client_side_encryption/data_key_spec.rb
- spec/mongo/client_encryption_spec.rb
- spec/mongo/crypt/explicit_encryption_context_spec.rb
- spec/support/crypt.rb
- spec/support/matchers.rb
Also change the return type of `ClientEncryption#create_data_key` as mandated by the spec.
> RUBY-2152 Implemented "data key and double encryption" prose test

- lib/mongo/server/connection_base.rb
- lib/mongo/socket.rb
- spec/integration/size_limit_spec.rb
- spec/integration/test_bson_size_spec.rb
- spec/mongo/server/connection_spec.rb
https://jira.mongodb.com/browse/RUBY-1151
> Fix RUBY-1151 Commands should have a limit of maxBsonObjectSize + 16K

- docs/tutorials/client-side-encryption.txt
- docs/tutorials/ruby-driver-create-client.txt
This PR adds an `auto_encryption_options` section to the Client Ruby options documentation and makes some improvements to the Client-Side Encryption documentation.
Client-Side Encryption documentation Improvements:
- Add documentation required by the spec to the documentation
- Convert db and collection names from symbols to strings
- Remove unnecessary curly braces
- Add comments about expected results to the code
- Add a section about auto encryption options, which should provide more info about spawning mongocryptd
- Break up big code examples into three major steps and explain why those steps are necessary (envelope encryption)
See the Ruby options documentation on staging [here](https://docs-mongodbcom-staging.corp.mongodb.com/ruby-driver/root/master/tutorials/ruby-driver-create-clien …
> RUBY-2173 Improvements to Client-Side Encryption documentation

- README.md
- mongo.gemspec
JIRA: https://jira.mongodb.org/browse/DOCSP-9414
Please advise on what should be done with the gemspec that references the google group as the mailing list. Thanks!
> DOCSP-9414: Replace Google Groups with MongoDB Community Forum

- .evergreen/config.yml
- lib/mongo/crypt/encryption_io.rb
- spec/integration/client_side_encryption/auto_encryption_bulk_writes_spec.rb
- spec/integration/client_side_encryption/auto_encryption_command_monitoring_spec.rb
- spec/integration/client_side_encryption/auto_encryption_mongocryptd_spawn_spec.rb
- spec/integration/client_side_encryption/auto_encryption_old_wire_version_spec.rb
- spec/integration/client_side_encryption/auto_encryption_reconnect_spec.rb
- spec/integration/client_side_encryption/auto_encryption_spec.rb
- spec/integration/client_side_encryption/bson_size_limit_spec.rb
- spec/integration/client_side_encryption/bypass_mongocryptd_spawn_spec.rb
- spec/integration/client_side_encryption/client_close_spec.rb
- spec/integration/client_side_encryption/corpus_spec.rb
- spec/integration/client_side_encryption/data_key_spec.rb
- spec/integration/client_side_encryption/external_key_vault_spec.rb
- spec/integration/client_side_encryption/views_spec.rb
- spec/mongo/client_encryption_spec.rb
- spec/mongo/crypt/auto_encrypter_spec.rb
- spec/runners/transactions.rb
- spec/spec_tests/client_side_encryption_spec.rb
- spec/support/crypt.rb
Changes in this PR:
- Run FLE tests on a replica set in CI
- In the FLE prose tests, perform all key vault operations using write concern majority
- Fix all instances of db/collection names as symbols.
> RUBY-2147 Run FLE tests on replica set

- .evergreen/config.yml
- spec/README.md
- spec/integration/client_construction_spec.rb
- spec/integration/client_side_encryption/auto_encryption_bulk_writes_spec.rb
- spec/integration/client_side_encryption/auto_encryption_command_monitoring_spec.rb
- spec/integration/client_side_encryption/auto_encryption_old_wire_version_spec.rb
- spec/integration/client_side_encryption/auto_encryption_reconnect_spec.rb
- spec/integration/client_side_encryption/auto_encryption_spec.rb
- spec/integration/client_side_encryption/bson_size_limit_spec.rb
- spec/integration/client_side_encryption/bypass_mongocryptd_spawn_spec.rb
- spec/integration/client_side_encryption/client_close_spec.rb
- spec/integration/client_side_encryption/corpus_spec.rb
- spec/integration/client_side_encryption/data_key_spec.rb
- spec/integration/client_side_encryption/external_key_vault_spec.rb
- spec/integration/client_side_encryption/views_spec.rb
- spec/integration/client_update_spec.rb
- spec/mongo/crypt/auto_encrypter_spec.rb
- spec/support/crypt.rb
- spec/support/spec_config.rb
- spec/support/utils.rb
This PR allows a developer to specify a non-default port on which to run mongocryptd through an environment variable. Evergreen has mongocryptd listening on port 27090, allowing us to run tests on sharded clusters. This option could eventually be replaced with a URI option.
> RUBY-2147 Run FLE tests on sharded cluster

- lib/mongo/monitoring/event/secure.rb
- spec/README.md
- spec/support/spec_config.rb
https://jira.mongodb.com/browse/RUBY-1999
- Add MONGO_RUBY_DRIVER_UNREDACT_EVENTS environment variable to omit command event payload redaction, for assistance with e.g. auth or user management debugging
- Rename CLIENT_DEBUG to MONGO_RUBY_DRIVER_CLIENT_DEBUG for consistency with our other environment variables in the test suite
- Document MONGO_RUBY_DRIVER_CLIENT_DEBUG
> RUBY-1999 improve command monitoring diagnostics

- .dockerignore
- .evergreen/Dockerfile.erb
- .evergreen/run-tests.sh
- .evergreen/tools.rb
- .gitignore
https://jira.mongodb.com/browse/RUBY-1999
- Improve efficiency of docker provisioning by eliminating redundant stores of toolchain and server tarballs
- Exclude all files beginning with .env.private from git and docker
- Support ubuntu1804 in Docker
> RUBY-1999 Evergreen/Docker tooling changes

- .evergreen/config.yml
- lib/mongo/error/bulk_write_error.rb
- lib/mongo/error/notable.rb
- spec/mongo/bulk_write/result_spec.rb
- spec/mongo/error/bulk_write_error_spec.rb
- spec/mongo/error/notable_spec.rb
This error was surfacing in the FLE replica set tests, but that's just the only place we test 4.2 replica sets against ruby-2.3.
> Fix Ruby 2.3 Replica Set Errors

- .evergreen/Dockerfile.erb
- .evergreen/config.yml
- .evergreen/functions.sh
- gemfiles/standard.rb
- spec/lite_spec_helper.rb
- Add tooling to show memory/cpu use by test suite
- Reduce heap size hard limit for jruby from 2g to 1.5g
- Stop installing bundler on jruby, it is now installed in the toolchain
- Fix autoloads not autoloading
- Use rhel instead of ubuntu which fixes the tests
> JRuby failure debugging

- lib/mongo/client_encryption.rb
- lib/mongo/crypt/auto_decryption_context.rb
- lib/mongo/crypt/binding.rb
- lib/mongo/crypt/context.rb
- lib/mongo/crypt/encryption_io.rb
- lib/mongo/crypt/explicit_encrypter.rb
- lib/mongo/crypt/explicit_encryption_context.rb
- lib/mongo/crypt/hooks.rb
- lib/mongo/error/parser.rb
- lib/mongo/grid/file/info.rb
- lib/mongo/monitoring/event/cmap/connection_check_out_failed.rb
- lib/mongo/operation/shared/response_handling.rb
- lib/mongo/protocol/msg.rb
- lib/mongo/retryable.rb
- lib/mongo/server/connection_pool/populator.rb
- lib/mongo/session.rb
- lib/mongo/uri.rb
- lib/mongo/uri/srv_protocol.rb
The culprit was mostly lib/mongo/crypt/binding.rb. Because most of the methods in that file are metaprogrammed, I had to use the `@!method` tag, which I hadn't known about before!
> RUBY-2177 Fix all API documentation warnings

- lib/mongo/client.rb
- lib/mongo/crypt/auto_encrypter.rb
- lib/mongo/crypt/handle.rb
- spec/integration/client_construction_spec.rb
- spec/integration/client_update_spec.rb
- spec/mongo/crypt/handle_spec.rb
When testing this change, I realized that the client would leak background threads if it raised an error while building the encrypter, so I added a fix and tests for that as well.
> RUBY-2176 Raise an error if an encryption client is initialized with empty string AWS credentials

- lib/mongo/crypt/encryption_io.rb
- lib/mongo/database.rb
- lib/mongo/operation/insert/command.rb
- lib/mongo/operation/insert/legacy.rb
- lib/mongo/operation/insert/op_msg.rb
- lib/mongo/operation/shared/executable.rb
- lib/mongo/operation/shared/op_msg_or_command.rb
- lib/mongo/protocol/bit_vector.rb
- lib/mongo/protocol/message.rb
- lib/mongo/protocol/msg.rb
- lib/mongo/protocol/serializers.rb
- lib/mongo/server/connection.rb
- lib/mongo/server/connection_base.rb
- spec/integration/client_side_encryption/auto_encryption_mongocryptd_spawn_spec.rb
- spec/integration/crud_spec.rb
**The Problem:** During automatic encryption, commands are sent to mongocryptd to have encryption placeholders added to them. The response from mongocryptd is deserialized without the `mode: :bson` flag, causing command fields that were previously BSON types (e.g. Int64s) to be deserialized into Ruby types (e.g. Ruby integers). This means that the driver can lose type information on non-encrypted fields when writing them to the database using automatic encryption.
**The Fix:** Allow commands to pass an option called `deserialize_as_bson` to the execution code and down to the protocol layer, which will then deserialize responses from the server using the `mode: :bson` option. This isn't included on all commands because it would create a significant change in driver behavior, so it is only …
> RUBY-2119 Do not lose type information when writing documents with automatic encryption

- lib/mongo/operation/drop/command.rb
- lib/mongo/operation/drop_database/command.rb
- lib/mongo/operation/drop_index/command.rb
- lib/mongo/operation/insert.rb
- lib/mongo/operation/insert/command.rb
- lib/mongo/operation/insert/legacy.rb
- lib/mongo/operation/kill_cursors/command.rb
- lib/mongo/operation/op_msg_base.rb
- lib/mongo/operation/shared/limited.rb
- lib/mongo/operation/shared/specifiable.rb
- lib/mongo/operation/shared/write.rb
- lib/mongo/operation/update/command.rb
- lib/mongo/operation/update_user/command.rb
- spec/mongo/operation/limited_spec.rb
https://jira.mongodb.com/browse/RUBY-2219
Read preference code in the operation layer expects a server to be provided, but some of the methods involved defaulted their server argument to nil which didn't make sense. Make the server argument required everywhere along the call chain to the methods that calculate the read preference.
> RUBY-2219 make server arguments required

- lib/mongo/bulk_write.rb
- lib/mongo/operation/shared/executable.rb
- lib/mongo/operation/shared/response_handling.rb
- lib/mongo/operation/shared/write.rb
- lib/mongo/retryable.rb
- lib/mongo/session.rb
- spec/integration/retryable_bulk_write_spec.rb
- spec/integration/retryable_writes_spec.rb
- spec/mongo/retryable_spec.rb
This PR should not modify existing retryable writes functionality at all. It only changes the implementation to use the RetryableWriteError label. I will create a follow-up PR to add functionality specific to server version 4.4.
> RUBY-2044 Part I: Modify existing retryable writes functionality to use the RetryableWriteError label

- lib/mongo/operation/shared/response_handling.rb
- lib/mongo/retryable.rb
- spec/integration/legacy_retryable_writes_spec.rb
- spec/integration/retryable_bulk_write_spec.rb
- spec/mongo/retryable_spec.rb
This PR should not change user-facing behavior. I have added an integration test for legacy retryable writes because I could not find any integration tests for that behavior.
> RUBY-2044 Part II: Update legacy retries to use RetryableWriteError label

- .evergreen/Dockerfile.erb
- .evergreen/config.yml
- .evergreen/run-tests-kerberos-integration.sh
- gemfiles/mongo_kerberos.gemfile
- lib/mongo/auth.rb
- lib/mongo/auth/aws.rb
- lib/mongo/auth/base.rb
- lib/mongo/auth/conversation_base.rb
- lib/mongo/auth/cr.rb
- lib/mongo/auth/gssapi.rb
- lib/mongo/auth/gssapi/conversation.rb
- lib/mongo/auth/scram.rb
- lib/mongo/auth/scram_conversation_base.rb
- lib/mongo/auth/x509.rb
- lib/mongo/server/pending_connection.rb
- spec/lite_spec_helper.rb
- spec/mongo/auth/cr_spec.rb
- spec/mongo/auth/gssapi/conversation_spec.rb
- spec/mongo/auth/invalid_mechanism_spec.rb
- spec/mongo/auth/ldap/conversation_spec.rb
- spec/mongo/auth/ldap_spec.rb
- spec/mongo/auth/scram/conversation_spec.rb
- spec/mongo/auth/scram256/conversation_spec.rb
- spec/mongo/auth/scram_negotiation_spec.rb
- spec/mongo/auth/scram_spec.rb
- spec/mongo/auth/user_spec.rb
- spec/mongo/auth/x509/conversation_spec.rb
- spec/mongo/auth/x509_spec.rb
- spec/mongo/auth_spec.rb
This PR removes JRuby/Kerberos configurations until the JRuby native gssapi implementation is unbroken.
> RUBY-2196 Move Kerberos auth mechanism and conversation to driver

- lib/mongo/server/connection.rb
- lib/mongo/server/monitor/connection.rb
- spec/mongo/server/monitor_spec.rb
> RUBY-2132 handshake even when monitoring connection has no metadata and remove some deprecated code from monitor connection

- lib/mongo/error/operation_failure.rb
- spec/integration/change_stream_spec.rb
[RUBY-2238](https://jira.mongodb.org/browse/RUBY-2238)
I believe we never ended up syncing the spec tests that tested whether ElectionInProgress was a resumable change stream error, so the spec tests are already up to date. I added an integration test just to sanity check that this change actually did something.
> RUBY-2238 remove ElectionInProgress from resumable change stream error list

- .evergreen/config.yml
- .evergreen/functions-config.sh
- .evergreen/run-tests.sh
- lib/mongo/monitoring/command_log_subscriber.rb
- lib/mongo/monitoring/event/command_started.rb
- lib/mongo/monitoring/publishable.rb
- lib/mongo/server/connection.rb
- lib/mongo/server/connection_base.rb
- lib/mongo/server/connection_common.rb
- lib/mongo/server/connection_pool.rb
- lib/mongo/server/monitor/connection.rb
- spec/README.md
- spec/integration/fork_reconnect_spec.rb
- spec/integration/reconnect_spec.rb
- spec/integration/sdam_error_handling_spec.rb
- spec/mongo/cluster_spec.rb
- spec/mongo/server/connection_spec.rb
- spec/mongo/server/monitor/connection_spec.rb
- spec/mongo/server/monitor_spec.rb
- spec/spec_tests/command_monitoring_spec.rb
- spec/stress/connection_pool_stress_spec.rb
- spec/stress/connection_pool_timing_spec.rb
- spec/stress/fork_reconnect_stress_spec.rb
- spec/support/lite_constraints.rb
- spec/support/spec_config.rb
- spec/support/utils.rb
- Remove pid checks from non-monitoring connections and place them into connection pool. This permits the pool to close/discard connections from the parent process in the child, instead of these connections getting reconnected in place.
- When operation on connections fail with network errors, mark connections as errored and do not check them into pools.
- The monitoring connections still need the pid check for the time being, moved it into the monitoring connection from connection base.
- Add an integration test for using monitoring connection after fork (this is transparently supported for now).
- Add an integration test for using a client after fork without reconnection. This does work  but new non-monitoring connections are created for …
> RUBY-2132 improve connection reconnection after fork

- lib/mongo/server/monitor.rb
- lib/mongo/server/monitor/connection.rb
- spec/integration/fork_reconnect_spec.rb
- spec/integration/heartbeat_events_spec.rb
- spec/integration/sdam_error_handling_spec.rb
- spec/mongo/server/monitor/connection_spec.rb
- spec/mongo/server/monitor_spec.rb
Instead of retrying once on a failing ismaster:
- Immediately mark the server unknown on ismaster failure
- If server was previously known, schedule another check immediately
(bypassing minimum interval)
This PR also uses the response from the initial handshake to perform the first sdam round.
> RUBY-2132 remove monitoring connection retries

- lib/mongo/operation/shared/sessions_supported.rb
- spec/integration/read_preference_spec.rb
- spec/mongo/operation/read_preference_op_msg_spec.rb
From the [server selection spec](https://github.com/mongodb/specifications/blob/4e570fc442e0a67bcb4999c85a0afb10c0c5a8ae/source/server-selection/server-selection.rst#passing-read-preference-to-mongos):
> Therefore, when sending queries to a mongos, the following rules apply:
>
> - For mode 'primary', drivers MUST NOT set the slaveOK wire protocol flag and MUST NOT use $readPreference
> - For mode 'secondary', drivers MUST set the slaveOK wire protocol flag and MUST also use $readPreference
> - For mode 'primaryPreferred', drivers MUST set the slaveOK wire protocol flag and MUST also use $readPreference
> - For mode 'secondaryPreferred', drivers MUST set the slaveOK wire protocol flag. If the read preference contains a non-empty tag_sets parameter, maxStalenessSeconds is a positive …
> RUBY-2184: Make $readPreference behave as specified

- lib/mongo/auth/aws/request.rb
- spec/mongo/auth/aws/request_spec.rb
Fixed issue where a call to formatted_time mutates the @time instance. Changed the call to utc to getutc.
> Fix RUBY-2279 AWS request mutates passed in time

- lib/mongo/client.rb
- spec/mongo/client_construction_spec.rb
The fix itself was omly a 2-3 line fix... but the testing was the real kicker. The tests work, but I modified a lot more code than maybe necessary... Let me know if I need to fix that.
> RUBY-2165 Yield client to block from constructor

- docs/tutorials/ruby-driver-authentication.txt
- docs/tutorials/ruby-driver-sessions.txt
- lib/mongo/client.rb
- spec/mongo/session_spec.rb
It seems like the with_session function on the client already closes the session on completion of the block. All I did was add some tests to make sure it works...
Some notes:
- I did this in `session_spec.rb` but perhaps it should have been in `client_spec.rb`
- When there is an error inside the `with_session` block, it is rescued and never re-raised.
> RUBY-1262 added tests for closing session after block

- lib/mongo/collection/view/readable.rb
- spec/mongo/collection_spec.rb
Worked on this with Emily. Checked for collation option in opts and if it doesn't exist get it from @options.
> RUBY-2295 include collation option in count_documents

- lib/mongo/cluster.rb
- lib/mongo/cluster/sdam_flow.rb
- lib/mongo/monitoring/event/server_description_changed.rb
- lib/mongo/monitoring/event/server_heartbeat_failed.rb
- lib/mongo/monitoring/event/server_heartbeat_started.rb
- lib/mongo/monitoring/event/server_heartbeat_succeeded.rb
- lib/mongo/monitoring/server_description_changed_log_subscriber.rb
- lib/mongo/server.rb
- lib/mongo/server/connection.rb
- lib/mongo/server/monitor.rb
- lib/mongo/server/monitor/connection.rb
- lib/mongo/server/push_monitor.rb
- lib/mongo/server/push_monitor/connection.rb
- lib/mongo/socket.rb
- lib/mongo/topology_version.rb
- lib/mongo/utils.rb
- spec/integration/awaited_ismaster_spec.rb
- spec/integration/connection_spec.rb
- spec/integration/heartbeat_events_spec.rb
- spec/integration/sdam_error_handling_spec.rb
- spec/integration/server_monitor_spec.rb
- spec/spec_tests/data/sdam_integration/isMaster-command-error.yml
- spec/spec_tests/data/sdam_integration/isMaster-timeout.yml
- spec/spec_tests/data/sdam_integration/rediscover-quickly-after-step-down.yml
- spec/spec_tests/sdam_integration_spec.rb
- spec/support/spec_config.rb
This PR adds awaited ismaster implementation and a push monitor that uses the exhausted awaited ismasters for 4.4+ servers.
> RUBY-2132 push monitor

- docs/tutorials/ruby-driver-crud-operations.txt
I built this locally and confirmed that this does not generate any new documentation warnings or errors.
> RUBY-2274: Make CRUD tutorial headers consistent with header nesting guide

- lib/mongo/collection/view/iterable.rb
- lib/mongo/retryable.rb
- spec/integration/query_cache_spec.rb
This code will further be modified to support caching multi-batch queries, but for now, I have eliminated the `Cannot restart iteration of a cursor which issued a getMore` exception from occurring when a user tries to iterate through a multi-batch result multiple times.
> RUBY-2338 Stop query cache from caching multi-batch queries

- lib/mongo/collection/view/readable.rb
This PR is a minor fix of documentation: **new view** was not visible.
> Documentation fix (minor)

- lib/mongo/collection/view/iterable.rb
- lib/mongo/query_cache.rb
- spec/mongo/query_cache_spec.rb
This PR does not change any behavior but implements methods in the query cache that abstract some of the behavior of creating a cache key and reading from/writing to the cache. These methods will be used to implement efficient limits in the query cache.
> RUBY-2340 Part 1: Refactor the query cache to implement read and write methods

- lib/mongo/collection/view/iterable.rb
- lib/mongo/query_cache.rb
- spec/integration/query_cache_spec.rb
- spec/mongo/query_cache_spec.rb
The goal of this PR is to have the query cache reuse the same query results when a query with the same or a lower limit as the stored results is executed.
Here is my general design:
* Remove the limit from the cache key
* When reading from the cache, check the limit on the cursor's view. If that limit is greater than or equal to the limit of the query currently being executed, then return that cached cursor.
* The query cache does not store more than one result for the same query with different limits. It stores the result thus far with the most permissive limit (either a large number or nil).
Let me know if you think there needs to be more comments in the code!
> RUBY-2340 Update the query cache to efficiently handle limits

- lib/mongo/caching_cursor.rb
- lib/mongo/collection/view/iterable.rb
- lib/mongo/retryable.rb
- spec/integration/query_cache_spec.rb
- spec/mongo/caching_cursor_spec.rb
I did this by modifying the CachingCursor so that it adds document to `@cached_docs` on `try_next` rather than `process`. This way, the cursor can iterate through the `@cached_docs` and then use `try_next` to iterate through the remaining documents, calling `get_more` if there are other batches of documents that haven't been fetched.
> RUBY-2367 Allow CachingCursor to cache multi-batch queries

- lib/mongo/collection/view/aggregation.rb
- lib/mongo/collection/view/iterable.rb
- lib/mongo/collection/view/readable.rb
- spec/integration/query_cache_spec.rb
This PR does two things:
1. It allows aggregations to be cached. Previously, trying to aggregate with the QueryCache turned on would have caused an error. Now, it caches the aggregation, taking into account read concern, read preference, and collation options. (All other options are specified in the pipeline).
2. It clears the query cache when $out or $merge stages are specified in an aggregation, since those stages can write to the collection.
Documentation on aggregation caching will be provided in a later ticket.
> RUBY-2377 Cache aggregations and clear the cache when $out or $merge stages provided

- lib/mongo/collection.rb
- lib/mongo/collection/view/aggregation.rb
- lib/mongo/collection/view/readable.rb
- lib/mongo/collection/view/writable.rb
- lib/mongo/query_cache.rb
- spec/integration/query_cache_spec.rb
- spec/mongo/query_cache_spec.rb
Currently, the query cache completely clears on every write operation. However, most write operations only impact one database and collection, so it doesn't make sense to clear every single cursor from the cache.
This PR introduces the following changes:
* The cache is now structured in two levels: the first-level key is the namespace (database.collection), and every value is a Hash containing CachingCursors.
* Instead of clearing the whole query cache, most write operations only clear the namespace that they're modifying.
* Aggregation results are cached at the `nil` namespace because aggregation pipelines can read data from multiple namespaces.
* Aggregation operations that write to a collection ($out and $merge stages) clear the entire cache.
> RUBY-2375 More efficient query cache invalidation

- docs/index.txt
- docs/ruby-driver-tutorials.txt
- docs/tutorials/query-cache.txt
- docs/tutorials/ruby-driver-crud-operations.txt
I have moved the query cache documentation to its own page and linked to it from the CRUD page. I have gone in depth on various topics, such as cache invalidation, using the query cache with transactions and aggregations, and queries with limits.
> RUBY-2376 Query cache documentation

- lib/mongo/collection/view/aggregation.rb
- lib/mongo/query_cache.rb
- spec/integration/query_cache_spec.rb
- spec/mongo/query_cache_spec.rb
I introduced a bug in the query cache by storing aggregations in the `nil` namespace -- if aggregations with the same pipeline were performed in two different namespaces, then the second one would return the cached results of the first. This PR adds namespace back to the cache key and introduces a new option (`multi_collection`) which indicates that results could come from multiple namespaces and should be stored under the `nil` namespace key.
> RUBY-2410 Fix issue where same aggregation occuring on different collection returns cached result

- docs/tutorials/query-cache.txt
- spec/integration/query_cache_spec.rb
I have opted here not to add cache invalidation to the helpers that modify those systems collections as that would be a fairly significant project if I tried to do it exhaustively. Instead, I added a documentation section explaining that system collections use the query cache and the data will not be invalidated, so users should disable the query cache if they need up to date systems collection information.
> RUBY-2413 Add a test and documentation for system collections with query cache

- lib/mongo/bulk_write.rb
- spec/integration/bulk_write_spec.rb
This behavior was documented in [this Google groups question](https://groups.google.com/g/mongodb-user/c/o1H5Q0PQJjs/m/jb2Vr4JDEQAJ?pli=1).
> RUBY-1131 Ensure that split bulk writes don't produce command failed event

- spec/integration/fork_reconnect_spec.rb
- spec/mongo/client_spec.rb
I wrote the tests given in the spec change [here](https://github.com/mongodb/specifications/commit/6a31988385f54e4ec9daddfbf21344a2a96e2656) and they pass on our current implementation.
> RUBY-1524 Test that driver session pool is cleared after forking

- lib/mongo/collection.rb
- spec/mongo/collection_spec.rb
I added more detailed error messages for when users insert nil or non-hash documents (as described [here](https://jira.mongodb.org/browse/RUBY-2399)) and wrote corresponding unit test cases.
> RUBY-2399 Provide more descriptive error message when inserting nil documents

- lib/mongo/collection/view/readable.rb
- spec/mongo/collection/view/readable_spec.rb
I added a check in estimated_document_count to raise an error if the filter hash is non-empty (as discussed [here](https://jira.mongodb.org/browse/RUBY-2349)), and I added corresponding unit tests.
> RUBY-2349 Raise error when estimated_document_count is called with filters

- spec/mongo/client_encryption_spec.rb
- spec/mongo/crypt/data_key_context_spec.rb
It looks like libmongocrypt has changed some of its KMS endpoint validation behavior -- now calling the Amazon KMS endpoint via https is valid, and the data key context object also performs some endpoint validation. This does not impact the user experience with FLE.
> Fix FLE tests

- lib/mongo/server/description.rb
- spec/mongo/server/description_spec.rb
`connectionId` does not represent state of the topology and as such should be excluded when comparing two Description objects.
> RUBY-2419 Exclude connectionId field when checking for equality

- spec/integration/bson_symbol_spec.rb
- spec/support/shared/protocol.rb
A couple tests were broken/fixed as a result of the bson jruby 4.11.0 release.
> Remove pending status from BSON Symbol test

- docs/reference/driver-compatibility.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-13536
> DOCSP-13536: remove MongoDB 2.4 from compatibility table

- .evergreen/config-atlas.yml
- .evergreen/config.yml
- .evergreen/config/axes.yml.erb
- .evergreen/config/standard.yml.erb
- .evergreen/functions.sh
- .evergreen/run-tests.sh
- docs/tutorials/ruby-driver-create-client.txt
- gemfiles/zstd_compression.gemfile
- lib/mongo/client.rb
- lib/mongo/protocol/compressed.rb
- lib/mongo/server/app_metadata.rb
- lib/mongo/server/monitor/connection.rb
- spec/README.md
- spec/integration/zstd_compression_spec.rb
- spec/mongo/client_construction_spec.rb
- spec/mongo/protocol/compressed_spec.rb
- spec/spec_tests/uri_options_spec.rb
Add support for zstd network compression (per DRIVERS-600) to the Ruby driver.
Note that this PR depends on https://github.com/mongodb-labs/mongo-ruby-spec-shared/pull/6 being merged for the specs to run.
> RUBY-1682: Add Zstandard (zstd) network compression support

- spec/mongo/server/app_metadata_shared.rb
- spec/support/spec_config.rb
This commit fixes an assumption that the spec is always executed on a
Linux machine.
> RUBY-2296: Fix app metadata spec

- lib/mongo/background_thread.rb
- lib/mongo/cluster.rb
- lib/mongo/monitoring.rb
- lib/mongo/server.rb
- lib/mongo/server/connection_base.rb
- lib/mongo/server/connection_pool.rb
- lib/mongo/server/description.rb
- lib/mongo/server/round_trip_time_averager.rb
- lib/mongo/server_selector/base.rb
- lib/mongo/session.rb
- lib/mongo/socket.rb
- lib/mongo/utils.rb
- spec/mongo/cluster_spec.rb
- spec/mongo/server/description_spec.rb
- spec/mongo/session_transaction_spec.rb
This PR introduces usage of monotonic clock instead of wall clock for measuring time. This ensures correct calculation of elapsed times.
See https://blog.dnsimple.com/2018/03/elapsed-time-with-ruby-the-right-way/ for details
> RUBY-2371: Use monotonic clock for measuring time

- spec/mongo/server/app_metadata_shared.rb
- spec/support/spec_config.rb
RUBY-2296: Fix app metadata spec
This commit fixes an assumption that the spec is always executed on a
Linux machine.
> RUBY-2296: Fix app metadata spec (#2208)

- lib/mongo/collection/view/change_stream.rb
- lib/mongo/cursor.rb
- lib/mongo/server/connection_base.rb
- lib/mongo/socket.rb
- spec/mongo/collection/view/change_stream_spec.rb
- spec/mongo/cursor_spec.rb
For details see https://github.com/mongodb/specifications/blob/master/source/change-streams/change-streams.rst#resume-process
> RUBY-1700 Ignore errors when killing change stream cursors when resuming

- .evergreen/config.yml
- .evergreen/config/standard.yml.erb
In addition, the buildvariant `kerberos-integration-ubuntu` is missing fields `mongodb-version` and `topology`. All other nodes have those fields, so you might want to check it.
> Fix .evergreen/config.yml line which should be commented

- docs/reference/client-side-encryption.txt
This corrects the broken links on the client-side-encryption page. It needs to be backported to all affected versions. The `:drivers:` role is added to the docs companion repo.
> correct links to csfle guide

- lib/mongo/server_selector/base.rb
Ignore read preference for $out/$merge on secondaries if any servers are pre-5.0.
> RUBY-2841 Ignore read pref if any pre-5.0

- lib/mongo/error/bulk_write_error.rb
- lib/mongo/error/operation_failure.rb
- spec/integration/bulk_write_error_message_spec.rb
- spec/mongo/error/operation_failure_heavy_spec.rb
I decided to add a details property to the `OperationFailure` class to better conform with the crud spec. 
This attribute is defined as follows:
- For WriteConcernErrors this is `document['writeConcernError']['errInfo']`.
- For WriteErrors this is `document['writeErrors'][0]['errInfo']`.
- For all other errors this is `nil`.
Now, this makes a lot of sense for the OperationFailure class, but for BulkWriteError it doesn't quite make sense. The problem is that BulkWriteError can have multiple writeErrors inside it. This is troublesome because I'm not sure what to do with the `details` now. Should it be a list of the `errInfo`s of each `writeError`? This didn't seem to make sense, so I just left the details off the `BulkWriteError` class. If the user wants to find that information, they can …
> RUBY-2525 Expose the Reason an Operation Fails Document Validation

- spec/mongo/auth/scram/conversation_spec.rb
- spec/mongo/auth/scram256/conversation_spec.rb
- spec/support/shared/scram_conversation.rb
The feature is already implemented in the driver. However, all tests assume that we use OP_QUERY. This PR changes theses tests to OP_MSG.
> RUBY-2762 Add tests for OP_MSG auth

- lib/mongo/cluster/reapers/cursor_reaper.rb
- lib/mongo/cursor.rb
- lib/mongo/cursor/kill_spec.rb
- spec/mongo/cluster/cursor_reaper_spec.rb
- spec/mongo/cursor_spec.rb
Finalizers are called from signal trap, so mutexes do not work there (see https://github.com/ruby/ruby/blob/master/thread_sync.c#L288).
> RUBY-2869 Do not use mutexes in finalizers

- .evergreen/config.yml
- .evergreen/config/standard.yml.erb
- .evergreen/run-tests-docker.sh
- lib/mongo/socket/ssl.rb
- spec/integration/client_side_encryption/custom_endpoint_spec.rb
https://jira.mongodb.com/browse/RUBY-2832
> RUBY-2832 Fix FLE on jruby-9.2 configuration in Evergreen

- spec/integration/grid_fs_bucket_spec.rb
Comparing the names is much less efficient than
comparing the instance directly.
It may also change in the future: https://bugs.ruby-lang.org/issues/18576
> Use encoding objects for comparison instead of encoding names

- .evergreen/functions-kerberos.sh
- README.md
- docs/index.txt
- docs/reference/client-side-encryption.txt
- docs/reference/create-client.txt
- docs/reference/crud-operations.txt
- docs/reference/transactions.txt
- lib/mongo/client.rb
- lib/mongo/collection.rb
- lib/mongo/collection/view/explainable.rb
- lib/mongo/database.rb
- lib/mongo/database/view.rb
- mongo.gemspec
- spec/README.md
- spec/spec_tests/data/crud/read/aggregate-collation.yml
- spec/spec_tests/data/crud/read/count-collation.yml
- spec/spec_tests/data/crud/read/distinct-collation.yml
- spec/spec_tests/data/crud/read/find-collation.yml
- spec/spec_tests/data/crud/write/bulkWrite-collation.yml
- spec/spec_tests/data/crud/write/deleteMany-collation.yml
- spec/spec_tests/data/crud/write/deleteOne-collation.yml
- spec/spec_tests/data/crud/write/findOneAndDelete-collation.yml
- spec/spec_tests/data/crud/write/findOneAndReplace-collation.yml
- spec/spec_tests/data/crud/write/findOneAndUpdate-collation.yml
- spec/spec_tests/data/crud/write/replaceOne-collation.yml
- spec/spec_tests/data/crud/write/updateMany-collation.yml
- spec/spec_tests/data/crud/write/updateOne-collation.yml
- spec/support/cluster_tools.rb
We've migrated docs to www.mongodb.com/docs. As such, this updates links in the source!
> DOCSP-20373 Update links to mongodb.com/docs

- lib/mongo/client.rb
- lib/mongo/collection.rb
- lib/mongo/collection/view/change_stream.rb
- lib/mongo/database.rb
This spec change was done in RUBY-1940 but the comments on the affected functions were not updated. The ticket can RUBY-2920 can be marked as a duplicate, since the work was already done.
> RUBY-2920 ChangeStream Spec: fullDocument field in ChangeStreamOptions should be an optional to handle "default" case.

- docs/reference/collection-tasks.txt
A lot of this is taken from the MongoDB docs on Time Series collections here: https://www.mongodb.com/docs/manual/core/timeseries-collections/#time-series-collections
In general I opted for less detail on exactly what everything does and more on how to do it in Ruby. If the users wants to know more about time series collections in general they should refer to the MongoDB docs. I have linked it in multiple places.
> RUBY-2715 Add documentation for Time Series collections

- lib/mongo/client.rb
- lib/mongo/collection.rb
- lib/mongo/collection/view/change_stream.rb
- lib/mongo/database.rb
- spec/runners/unified/change_stream_operations.rb
- spec/spec_tests/data/change_streams_unified/change-streams-pre_and_post_images.yml
RUBY-2891
I tested this locally on MongoDB 6.0.0-rc0
> RUBY-2891 Change streams support for user-facing  PIT pre- and post-images

- lib/mongo/bulk_write/result.rb
- lib/mongo/bulk_write/result_combiner.rb
- spec/mongo/bulk_write/result_spec.rb
- spec/mongo/bulk_write_spec.rb
All of the other Result classes descend form Operation::Result super class and therefore already have the acknowledged? method. This PR only adds it to the BulkWrite Result class.
> RUBY-2973 Add the acknowledged? field to the BulkWrite::Result class

- .github/workflows/test.yml
- spec/runners/unified/assertions.rb
This PR is to fix the following test:
```
Run Driver Tests / ubuntu-latest ruby-3.1 mongodb-5.1 replica_set (pull_request)
```
This PR adds a test for MongoDB 6.0
> RUBY-2977 Test against MongoDB 6.0; Fix GH actions: replace 5.1 with 6.0

- spec/runners/unified.rb
- spec/runners/unified/error.rb
- spec/runners/unified/test.rb
- spec/spec_tests/data/unified/valid-fail/operation-unsupported.yml
The idea was to follow PyMongo's lead here: https://github.com/mongodb/specifications/pull/1206#discussion_r865396986
> RUBY-2988 Add unified test format valid-fail test for unsupported operation

- lib/mongo/collection.rb
- spec/runners/unified/ddl_operations.rb
- spec/runners/unified/test.rb
- spec/spec_tests/data/collection_management/createCollection-pre_and_post_images.yml
- spec/spec_tests/data/collection_management/modifyCollection-pre_and_post_images.yml
RUBY-2971. Did not add the collMod spec tests since we don't have a modify collections helper function.
EDIT: Must review this PR first: https://github.com/mongodb/mongo-ruby-driver/pull/2488
I was able to add the modifyCollections test back after skipping unsupported operations.
> RUBY-2971 Add createCollection and collMod spec tests for changeStreamPreAndPostImages option

- spec/spec_tests/data/collection_management/clustered-indexes.yml
- spec/spec_tests/data/collection_management/createCollection-pre_and_post_images.yml
- spec/spec_tests/data/collection_management/modifyCollection-pre_and_post_images.yml
This PR is to update the spec tests with additional downstream changes on the corresponding drivers tickets.
The CI failures all look unrelated and additionally they come up on other PRs.
> RUBY-2959 RUBY-2971 forbid serverless

- spec/spec_tests/data/change_streams_unified/change-streams.yml
Syncing the change streams spec tests also implements RUBY-3001
> RUBY-2969 RUBY-3001 Always report 'wallTime' in the change stream event output

- lib/mongo/collection/view/readable.rb
- lib/mongo/operation/distinct/op_msg.rb
When I originally implemented this I incorrectly put the comment option inside the command... This PR moves it to its own option, which is consistent with the other commands.
> RUBY-3007 make comment its own option

- spec/lite_spec_helper.rb
- spec/support/spec_config.rb
The following changes to `lite_spec_helper.rb` are required for specs to run on Windows:
- Use "timeout" instead of "timeout_interrupt"
- Skip loading debug gems if neither is present
> RUBY-3038: Fix lite_spec_helper on Windows

- lib/mongo/collection/view/iterable.rb
- spec/mongo/collection/view/readable_spec.rb
https://jira.mongodb.org/browse/RUBY-3046
Original report:
`Mongo::Collection::View#no_cursor_timeout` stopped working at commit 2d9f0217ec904a1952a1ada2136502eefbca562e (version 2.16.0).
I offer a _spec_ as proof that it is no longer working.
The _spec_ is green at commit aab776ebdfb15ddb9765039f7300e15796de0c5c (last working commit).
I am myself working with MongoDB 4.4 and Ruby 2.6.
The _bug_ also renders Mongoid's `.no_timeout` ineffective (does nothing).
Do not hesitate to ask me questions if something is unclear. 😄
> RUBY-3046 send no_cursor_timeout to server again

- lib/mongo/collection.rb
I know that the Insert constructor takes the following option:
```
```
but it's not tested anywhere and it's not part of the specification. 
I don't think collation is relevant in this case.
> RUBY-1627 Document collection insert options

- docs/release-notes.txt
- lib/mongo/bulk_write.rb
- lib/mongo/collection.rb
- lib/mongo/collection/view/writable.rb
- spec/mongo/collection_crud_spec.rb
Hello,
As I mentioned on https://github.com/mongodb/mongo-ruby-driver/discussions/2430, we use `insert_many` with an enumerable instead of an array; we want to make sure it will continue to work into the future.
It would be great if you guys could include this test.  
I am happy to adjust the pull request as you see fit.
> RUBY-3087 reinstate ability to call insert_many with Enumerable inputs which are not Array instances

- docs/reference/driver-compatibility.txt
This PR does three things: 
- Remove drivers <2.5
- Remove server rapid release versions (5.1, 5.2)
- Updates the kerberos versioning (I'm not sure if this is actually correct but I don't recall us dropping support)
If these three things are okay, I will update the ticket (RUBY-2671) with these changes.
> RUBY-2671 remove old drivers, remove rapid releases, update kerberos compat

- docs/reference/client-side-encryption.txt
- lib/mongo/client.rb
- lib/mongo/crypt/auto_encrypter.rb
- lib/mongo/crypt/handle.rb
- spec/integration/client_side_encryption/mongocryptd_prose_spec.rb
- spec/mongo/crypt/handle_spec.rb
The cryptSharedRequired name was a typo. Other drivers refer to the option as cryptSharedLibRequired. See: https://github.com/mongodb/specifications/pull/1353
> Revert "RUBY-3184 Rename crypt_shared_lib_required (#2670)"

- .evergreen/config.yml
- .evergreen/config/standard.yml.erb
- .gitignore
After investigating the failing FLE JRuby tests, I found that they were passing when I ran them in an evergreen patch. This PR simply uncomments those formerly-failing JRuby tests. After inspecting their run, they are part of the set of failing tests, but they are failing because of the server change in how wildcard indexes are reported (see https://jira.mongodb.org/browse/RUBY-3216). The FLE tests themselves, for JRuby, appear to be passing.
> RUBY-3217 Restore formerly-failing jruby FLE tests

- spec/spec_tests/data/client_side_encryption/fle2-CreateCollection.yml
- spec/spec_tests/data/client_side_encryption/fle2-EncryptedFields-vs-EncryptedFieldsMap.yml
Syncs the fle2-CreateCollection and fle2-EncryptedFields-vs-EncryptedFieldsMap tests to this commit: https://github.com/mongodb/specifications/commit/8f6f4a3a1841c0301ca057e96afca6f4f46711a2
Ref: https://jira.mongodb.org/browse/RUBY-3227
> RUBY-3227 Update fle2-* tests to match name requirements 

- .rubocop.yml
- lib/mongo/server/app_metadata.rb
- lib/mongo/server/app_metadata/environment.rb
- lib/mongo/server/app_metadata/truncator.rb
- spec/integration/connection/faas_env_spec.rb
- spec/mongo/client_construction_spec.rb
- spec/mongo/cluster_spec.rb
- spec/mongo/server/app_metadata/environment_spec.rb
- spec/mongo/server/app_metadata/truncator_spec.rb
- spec/mongo/server/app_metadata_spec.rb
- spec/mongo/socket/ssl_spec.rb
This PR addresses DRIVERS-2209 and DRIVERS-2623. It adds a new (optional) `:env` key to the client document in the handshake, describing the current FaaS environment (if any). This PR also updates the logic to truncate the client document, to keep it under the maximum document size of 512 bytes. 
(Another PR is forthcoming to update the touched files to satisfy Rubocop.)
Ref: https://jira.mongodb.org/browse/RUBY-3152
> RUBY-3152 Collect FaaS platform info in handshake

- lib/mongo/server/app_metadata/environment.rb
- spec/integration/connection/faas_env_spec.rb
- spec/mongo/server/app_metadata/environment_spec.rb
A later spec change (https://github.com/mongodb/specifications/commit/27f9a691008538b939467581e56eaac66191e665) removed VERCEL_URL and changed the behavior when multiple names are present.
> RUBY-3152 FaaS environment detection spec changes

- .evergreen/config.yml
- .evergreen/config/standard.yml.erb
- .github/workflows/test.yml
- docs/reference/driver-compatibility.txt
- gemfiles/standard.rb
- spec/integration/retryable_writes_errors_spec.rb
- spec/mongo/client_spec.rb
- spec/support/aws_utils.rb
This PR adds ruby 3.2 to the CI matrices.
ref: https://jira.mongodb.org/browse/RUBY-3200
> RUBY-3200 add Ruby 3.2 to CI

- lib/mongo/crypt.rb
- lib/mongo/crypt/auto_encrypter.rb
- lib/mongo/crypt/explicit_encrypter.rb
- spec/mongo/crypt_spec.rb
Backport https://jira.mongodb.org/browse/RUBY-3252 to 2.18
> RUBY-3252 Show user friendly error if no ffi

- .evergreen/config.yml
- .evergreen/config/standard.yml.erb
- spec/mongo/protocol/msg_spec.rb
RUBY-1599 requires that we test the driver against BSON 5. It turns out, though, that we're already testing the driver against the BSON master branch. There was only one place where tests were being skipped if BSON 5 was present; the tests still pass, though, with that condition removed.
So, there's not much for this PR to do, aside from remove that condition, and do a little bit of cleanup.
> RUBY-1599 Test against BSON 5

- docs/index.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-31496
This PR fixes the link to the API documentation in the navigation bar.
> DOCSP-31496: fix API link

- docs/index.txt
Backports DOCSP-31496 ("fix API link") to 2.19-stable.
> DOCSP-31496 backport to 2.19 stable (fix API link)

- docs/index.txt
Backports DOCSP-31496 (Fix API link) to 2.18-stable.
> DOCSP-31496 backport to 2.18 stable (Fix API link)

- docs/index.txt
Backports DOCSP-31496 (Fix API link) to 2.17-stable.
> DOCSP-31496 (Fix API link) backport to 2.17 stable

- .evergreen/config.yml
- .evergreen/config/common.yml.erb
- .evergreen/run-tests-serverless.sh
This addresses serverless test failures that cropped up since 7.0.0 was added as a "production release" to full.json. The problem is that the 7.0.0 entry for full.json omits the download entries, and thus the serverless tests were unable to download the crypt_shared library (because the code was relying on full.json).
It turns out, however, that crypt_shared was already being downloaded previously in the task setup, using a different approach (`download-crypt.sh`). All that's needed is to propagate one of the variables forward to the `run-serverless-tests.sh` script, so that the script can see and use the already-downloaded crypt_shared library.
So, this addresses those failures. The bad news is that the serverless tests are still failing, but now due to a different error (see …
> RUBY-3308 Fixing serverless test failures

- .gitignore
- profile/benchmarking.rb
- profile/benchmarking/helper.rb
- profile/benchmarking/micro.rb
[The spec](https://github.com/mongodb/specifications/blob/master/source/benchmarking/benchmarking.rst) requires that each benchmark use a variable number of iterations:
> Unless otherwise specified, the number of iterations to measure per micro-benchmark is variable:
> 
> * iterations should loop for at least 1 minute cumulative execution time
> * iterations should stop after 100 iterations or 5 minutes cumulative execution time, whichever is shorter
> RUBY-3314 Implement variable iterations for benchmarks

- .evergreen/config.yml
- .evergreen/config/common.yml.erb
See https://jira.mongodb.org/browse/RUBY-3324
> RUBY-3324 expose $task_id to atlas setup/teardown so clusters are unique per invocation

- .evergreen/config.yml
- .evergreen/config/common.yml.erb
This PR adds the `execution` expansion to the process environment for setting up and tearing down Atlas clusters.
ref: https://jira.mongodb.org/browse/RUBY-3328
> RUBY-3328 Atlas cluster setup generating duplicate cluster names 

- docs/index.txt
- docs/reference/crud-operations.txt
- docs/tutorials.txt
Backport to 2.16-stable:
* DOCSP-32949: docs link to the BSON 4.x Tutorial
* resolve link errors
> DOCSP-32949: docs link to the BSON 4.x Tutorial

- lib/mongo/cluster.rb
- lib/mongo/cluster/topology/base.rb
- spec/mongo/client_construction_spec.rb
- spec/mongo/cluster_spec.rb
- spec/support/recording_logger.rb
Writes an information message to the log when the remote host is detected to be a CosmosDB or DocumentDB host.
ref: https://jira.mongodb.org/browse/RUBY-3296
> RUBY-3296 Write to log when non-genuine host is detected

- docs/reference/schema-operations.txt
- docs/reference/search-indexes.txt
- docs/release-notes.txt
Adding docs and release notes for the Atlas search index management API got overlooked when that ticket was finished. This makes sure those are added.
> RUBY-3353 Add docs for the Atlas search index management API

- docs/index.txt
Updating the link to the API documentation to the correct URL to fix broken link
[JIRA](https://jira.mongodb.org/browse/DOCSP-34643)
> DOCSP-34643 - Update API link

- docs/index.txt
Updating the link to the API documentation to the correct URL to fix broken link
Backport of https://github.com/mongodb/mongo-ruby-driver/pull/2812
> DOCSP-34643 - Fix API link

- lib/mongo/cluster.rb
- lib/mongo/collection.rb
- lib/mongo/operation/shared/executable.rb
- lib/mongo/operation/shared/response_handling.rb
- lib/mongo/session.rb
- lib/mongo/session/server_session.rb
- lib/mongo/session/server_session/dirtyable.rb
- lib/mongo/session/session_pool.rb
- spec/mongo/session/session_pool_spec.rb
- spec/runners/unified/support_operations.rb
- spec/spec_tests/data/sessions_unified/driver-sessions-dirty-session-errors.yml
Add a `dirty` flag to `ServerSession`, and set it when a network error occurs. When checking the session back into the session pool, discard the session if it was marked dirty.
ref: RUBY-1813, DRIVERS-649, also RUBY-3000, RUBY-3031
> RUBY-1813 Discard ServerSessions involved in network errors

- lib/mongo/uri.rb
- spec/mongo/uri_spec.rb
- spec/spec_tests/data/connection_string/invalid-uris.yml
- spec/spec_tests/data/connection_string/valid-options.yml
REF: https://jira.mongodb.org/browse/RUBY-3329, https://jira.mongodb.org/browse/DRIVERS-2679
> RUBY-3329 Connection String: make delimiting slash between hosts and options optional

- spec/mongo/collection_crud_spec.rb
- spec/mongo/operation/insert_spec.rb
- spec/runners/crud.rb
- spec/runners/crud/test.rb
REF: https://jira.mongodb.org/browse/RUBY-2254
> RUBY-2254 sort by id when comparing collection contents

- spec/atlas/atlas_connectivity_spec.rb
The Atlas connectivity specs were failing when testing the "free tier" atlas URI, because the "ismaster" command wasn't returning the expected results.
Looking at the Go and Python drivers, it looks like they are only testing for the absence of an error when executing these commands; the original ticket (https://jira.mongodb.org/browse/DRIVERS-382) also stipulates that drivers should merely "verify that no error occurred." I've updated the specs so they no longer check for the contents of the result, and only confirm that no error occurred.
> Fix failing atlas connectivity specs

- docs/reference/create-client.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37038
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/ruby-driver/DOCSP-37038/reference/create-client/
> DOCSP-37038: Fix broken link

- docs/reference/create-client.txt
(cherry picked from commit e459c3f75f1b1a2181b8d468751580664a3e9e04)
Backport of #2841
> DOCSP-37038: Fix broken link (#2841)

- docs/index.txt
- docs/reference/create-client.txt
- docs/reference/crud-operations.txt
- docs/release-notes.txt
- docs/tutorials.txt
Applies changes from #2832 to the 2.19 branch
JIRA - https://jira.mongodb.org/browse/DOCSP-37137
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/ruby-driver/DOCSP-37137/
Build log - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65dd05377111165982852cda
> DOCSP-37137: Update BSON page references

- .gitmodules
- mongo.gemspec
- spec/integration/client_side_encryption/corpus_spec.rb
BSON 5 is released, so the Ruby driver ought to support it.
> MONGOID-5739 Support BSON 5

- .evergreen/config.yml
- .evergreen/config/axes.yml.erb
- .evergreen/config/standard.yml.erb
- .evergreen/update-evergreen-configs
- .github/workflows/test.yml
- docs/reference/driver-compatibility.txt
- docs/release-notes.txt
- lib/mongo/version.rb
Preparing for the 2.20 release. I probably did not need to deprecate 2.7 and JRuby 9.2, and add JRuby 9.4, in this release, but I did it anyway. :) The effort involved was minimal.
N.B.: The two failing specs are known and will be addressed in RUBY-3423 (related to `rangePreview` on latest server).
Proposed release announcement:
> Ruby Driver 2.20.0 Released
> 
> Version 2.20.0 of the Ruby driver for MongoDB is released. This adds the following new features:
> 
> * Connection strings no longer require a slash between the hosts and the options. E.g., "mongodb://example.com?w=1" and "mongodb://example.com/?w=1" are both valid connection strings now. (https://jira.mongodb.org/browse/RUBY-3329)
> * Container runtime and orchestration metadata for the client environment are now sent to the …
> RUBY-3424 Prep for 2.20

- release/mri/Dockerfile
The `bundle` step was failing during the release process, because it needed libz for libxml, for nokogiri, etc.
Also bumping to debian:12 for grins.
> Fixing the Dockerfile used for releasing gems

- docs/reference/create-client.txt
- lib/mongo/config.rb
The current documentation is both wordy and missing key information.
See also: https://github.com/mongodb/mongoid/pull/5808
> RUBY-3434: Improve documentation for forking servers

- lib/mongo/bulk_write.rb
- lib/mongo/collection/view/iterable.rb
- lib/mongo/collection/view/readable.rb
- lib/mongo/database.rb
- lib/mongo/database/view.rb
- lib/mongo/index/view.rb
- lib/mongo/operation/find/op_msg.rb
- lib/mongo/retryable/read_worker.rb
- spec/runners/unified/crud_operations.rb
- spec/runners/unified/ddl_operations.rb
- spec/spec_tests/data/client_side_operations_timeout/retryability-legacy-timeouts.yml
- spec/spec_tests/data/client_side_operations_timeout/retryability-timeoutMS.yml
Should be merged after https://github.com/mongodb/mongo-ruby-driver/pull/2865
> RUBY-3390 CSOT for list collections

- sbom.json
This PR adds an empty SBOM lite file so the product can be onboarded to Silk. This is necessary to then download the full SBOM upon releasing a new version.
Note: please advise if you'd rather have this file live in a different folder.
> RUBY-3488: Add empty SBOM lite file

- .github/workflows/cleanup.yml
- .github/workflows/release.yml
- Rakefile
This PR addresses the following issues:
* RUBY-3357 "Incorporate static code analysis tooling into pre-release process"
* RUBY-3449 "Integrate with Silk and generate SBOM documents for releases"
* RUBY-3450 "Integrate static analysis for releases"
* RUBY-3452 "Report authorized publication to distribution channels for releases"
With these working in the driver, it should be fairly straighforward to implement these in our other Ruby projects as well.
> RUBY-3357 SSDLC Requirements

- lib/mongo/retryable/base_worker.rb
- lib/mongo/retryable/read_worker.rb
- lib/mongo/retryable/write_worker.rb
- spec/integration/retryable_reads_errors_spec.rb
> [RUBY-3496] Fix legacy read pool retry error

- lib/mongo/version.rb
Prepping for 2.20.1. Proposed release notes follow; please edit as needed.
---
Version 2.20.1 of the [MongoDB Ruby Driver](https://rubygems.org/gems/mongo) is now available.
**Release Highlights**
This patch release includes one bug fix, and one documentation update:
* [RUBY-3496](https://jira.mongodb.org/browse/RUBY-3496) Certain retryable errors were not being retried when legacy retries were enabled. Thank you to Joe Lim for the PR!
* [RUBY-3434](https://jira.mongodb.org/browse/RUBY-3434) Documentation was added/improved to suggest how to configure Mongoid for use with forking web servers. Thank you to Johnny Shields for the PR!
Other changes (not user-visible):
* [RUBY-3396](https://jira.mongodb.org/browse/RUBY-3396) Added a test to ensure that no error is raised when the …
> RUBY-3507 Prep for 2.20.1

- README.md
- lib/mongo/server/description/features.rb
Modified the README.md to indicate the docs folder that was in the Ruby Driver can now be found in docs-ruby
> RUBY-3514 pointer to docs

- .evergreen/config.yml
- .evergreen/config/common.yml.erb
RUBY-3543
Evergreen config values have been updated, but the new `DRIVERS_ATLAS_BASE_URL` variable needs to be passed on to each script creating a cluster for Lambda.
> RUBY-3543 Run lambda tests on cloud-dev

- spec/spec_tests/data/sdam/rs/too_old.yml
- spec/spec_tests/data/sdam/sharded/too_new.yml
No user facing changes. Syncs the specs that were changed in DRIVERS-2250.
> RUBY-3330 sync sdam specs for too_old/too_new

- lib/mongo/crypt/binary.rb
- lib/mongo/crypt/binding.rb
- profile/driver_bench/crypto/decrypt.rb
- profile/driver_bench/rake/tasks.rake
- spec/mongo/crypt/binding/binary_spec.rb
- spec/mongo/crypt/binding/context_spec.rb
- spec/mongo/crypt/helpers/mongo_crypt_spec_helper.rb
This adds a benchmark for testing the performance of decrypting a document with a large number of encrypted fields (1500), and then changes the implementation so that it accesses the underlying fields of `mongocrypt_binary_t` directly, rather than indirectly.
The resulting performance improvements are marginal, but consistent:
```
with indirect mongocrypt_binary_t access:
thread_count=1; median ops/sec=44
thread_count=2; median ops/sec=48
thread_count=8; median ops/sec=78
thread_count=64; median ops/sec=327
with direct mongocrypt_binary_t access:
thread_count=1; median ops/sec=47
thread_count=2; median ops/sec=52
thread_count=8; median ops/sec=82
thread_count=64; median ops/sec=360
```
> RUBY-3299 Direct access to `mongocrypt_binary_t` for better decryption performance

- spec/spec_tests/data/client_side_operations_timeout/command-execution.yml
- spec/spec_tests/data/sdam_unified/hello-command-error.yml
- spec/spec_tests/data/sdam_unified/hello-network-error.yml
- spec/spec_tests/data/sdam_unified/interruptInUse-pool-clear.yml
- spec/spec_tests/data/sdam_unified/minPoolSize-error.yml
This syncs a few specs from DRIVERS-1725 to enable some tests on earlier server versions.
Note that one test from the original ticket (source/load-balancers/tests/sdam-error-handling.yml) was not synced; the Ruby driver does not have most of the load-balancers specs, and adding that one introduced numerous failures. There is probably an earlier spec that needs to be addressed there.
> RUBY-3461 Enable tests that require failCommand with appName on initial handshake before 4.9

- .evergreen/config.yml
- .evergreen/config/axes.yml.erb
- .evergreen/config/standard.yml.erb
- .evergreen/functions-kerberos.sh
- .evergreen/run-tests-kerberos-integration.sh
- .evergreen/run-tests.sh
- .github/workflows/test.yml
- .gitmodules
- spec/README.aws-auth.md
- spec/README.md
- spec/support/certificates/README.md
Many of the specs in evergreen were still using `mongo` instead of `mongosh` to configure the server. As `mongo` is no longer available with more recent server versions, this limited the server version we could use for some tests. Updating to `mongosh` lets us update those tests.
> RUBY-3164 Use mongosh instead of mongo

- lib/mongo/auth/credential_cache.rb
Fixes: https://jira.mongodb.org/browse/RUBY-3604
This PR fixes a race-condition that we occasionally see when multiple threads are simultaneously authenticating with the database.
Details of the failure:
While the cache is being written to, the value will go through a phase, such that if it is retrieved a particular moment, it will return false (value is never actually set to false by the code, somehow the underlying Ruby code behaves this way). The cache code does check if the value is nil, but will consider the value false to be a cache hit. As a result, The methods client_key and server_key in scram_conversion_base.rb may incorrectly return false instead of the value from the block. This will result in an error "no implicit conversion of false into String" when attempting to use the …
> RUBY-3604 Fix multithread auth race condition

- mongo.gemspec
TL;DR: let's not bundle specs with the packaged gem, because the specs as presented in the gem are not runnable anyway.
The `mongo` gem currently includes the spec files, presumably so that users can run the specs to ensure correctness. However, the `mongo-ruby-spec-shared` and `drivers-evergreen-tools` submodules are *not* included, which means (1) a symbolic link in `spec/support` that points into `.mod/drivers-evergreen-tools` causes a warning when installing the gem, and (2) the specs can't run anyway, because the submodules are missing.
Further, the specs require dependencies from the `testing` group in the Gemfile, which are not installed by default when the gem is installed, further complicating the running of specs from an installed gem.
So, because the specs cannot currently be …
> RUBY-2467 Remove specs from packaged gem

- README.md
Jira Ticket: https://jira.mongodb.org/browse/DOCSP-48221
This should fix the 404 by replacing the file path with an actual link to the file. Will have to regenerate the API docs as well.
> DOCSP-48221 Fix 404 in API Docs

- lib/mongo/version.rb
Release candidate for 2.21.1.
Version 2.21.1 of the MongoDB Ruby Driver is now available. This is the latest patch release in the 2.21 series.
Install it via RubyGems at the command line:
```
$ gem install -v 2.21.1 mongo
```
Or via Bundler, in a Gemfile:
```
gem 'mongo', '2.21.1'
```
It includes the following bug fixes:
- RUBY-3604 Fix a race condition in the authentication flow that could cause authentication to fail incorrectly when multiple simultaneous threads are attempting to authenticate. ([PR](https://github.com/mongodb/mongo-ruby-driver/pull/2912) by @jteich)
- RUBY-3658 When a timeout is specified on the client, database, or operation, partial writes to the server are never completed, resulting in timeouts. ([PR](https://github.com/mongodb/mongo-ruby-driver/pull/2927))
> Prepare for 2.21.1

- .evergreen/config.yml
The perf.send functionality in evergreen is no longer maintained and is not the preferred method of sending performance data to the signal processing service. This PR updates the evergreen yaml file to instead send the data down stream using the preferred performance-monitoring-api.corp.mongodb.com/raw_perf_results/cedar_report end point.
Changes were tested in [this patch](https://spruce.mongodb.com/version/681a5529b6001200076a889d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
> DEVPROD-17450 - Replace perf.send with new direct end point

- .github/workflows/release.yml
- Rakefile
- lib/mongo/version.rb
- product.yml
This adds the necessary bits for the new release automation process. Notably:
- Adds new `candidate:*` rake tasks, for previewing and creating candidate pull requests.
- Adds a `product.yml` file, which is used by the new `candidate:*` rake tasks.
- Updates the release workflow to use the new check/build/publish jobs.
> RUBY-3410 Release automation

- lib/mongo/version.rb
- product.yml
The MongoDB Ruby team is pleased to announce version 2.21.2 of the `mongo` gem - a pure-Ruby driver for connecting to, querying, and manipulating MongoDB databases. This is a new patch release in the 2.21.x series of the MongoDB Ruby Driver.
Install this release using [RubyGems](https://rubygems.org/) via the command line as follows: 
~~~
gem install -v 2.21.2 mongo
~~~
Or simply add it to your `Gemfile`:
~~~
gem 'mongo', '2.21.2'
~~~
Have any feedback? Click on through to MongoDB's JIRA and [open a new ticket](https://jira.mongodb.org/projects/RUBY) to let us know what's on your mind 🧠.
* [RUBY-3680](https://jira.mongodb.org/browse/RUBY-3680) Close pipe fds ([PR](https://github.com/mongodb/mongo-ruby-driver/pull/2936))
> Release candidate for 2.21.2

- .evergreen/config.yml
- .evergreen/config/common.yml.erb
- spec/integration/ocsp_verifier_spec.rb
- spec/support/certificates/atlas-ocsp-ca.crt
- spec/support/certificates/atlas-ocsp.crt
This reverts commit 0002cf81efd49fa6eec3dc61467aa3e710a49577, which added the serverless proxy rollout tests.
> RUBY-3515 Remove Serverless Proxy Incremental Rollout Tests

- lib/mongo/socket/ssl.rb
One more issue related to the OCSP stuff -- just a warning if the issuer certificate cannot be found. Copilot caught the lack of this check, and upon checking other drivers, Python (at least) takes the "warn and return" approach.
> RUBY-3694 Gracefully handle the case where the issuer can't be found

- lib/mongo/version.rb
- product.yml
The MongoDB Ruby team is pleased to announce version 2.21.3 of the `mongo` gem - a pure-Ruby driver for connecting to, querying, and manipulating MongoDB databases. This is a new patch release in the 2.21.x series of the MongoDB Ruby Driver.
Install this release using [RubyGems](https://rubygems.org/) via the command line as follows: 
~~~
gem install -v 2.21.3 mongo
~~~
Or simply add it to your `Gemfile`:
~~~
gem 'mongo', '2.21.3'
~~~
Have any feedback? Click on through to MongoDB's JIRA and [open a new ticket](https://jira.mongodb.org/projects/RUBY) to let us know what's on your mind 🧠.
* [RUBY-3694](https://jira.mongodb.org/browse/RUBY-3694) Use correct CA when verifying OCSP endpoint ([PR](https://github.com/mongodb/mongo-ruby-driver/pull/2944))
> Release candidate for 2.21.3
